use tadreebi_deplom;

drop table if exists all_tasnif_sa;
create table all_tasnif_sa
(
    est varchar(200),
    school_id  int(11), 
    pt_license varchar(30),
    city varchar(128),
    division varchar(200),
    name_pt varchar(200),
    course_program_id  bigint(20),
    pt_deplom_id  int(11), 
    code_sa varchar(64),
    name_sa varchar(200),
    level varchar(64),
    code_level varchar(64),
    levels_template_id smallint(4),
    school_level_order smallint(3),
    level_class_order smallint(3)
    
) ENGINE=MyISAM DEFAULT CHARSET=utf8;





insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب','جدة','التقنية الإدارية','إدارة وتطوير الموارد البشرية','04130203','تطوير الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب','جدة','التقنية الإدارية','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب','جدة','الحاسب وتقنية المعلومات','برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب','مكة المكرمة','التقنية الإدارية','إدارة وتطوير الموارد البشرية','04130203','تطوير الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب','مكة المكرمة','التقنية الإدارية','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب','مكة المكرمة','التقنية الإدارية','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب','مكة المكرمة','التقنية الإدارية','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب','مكة المكرمة','السكرتارية والأعمال المكتبية','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب ','ينبع','التقنية الإدارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي العالي للتدريب ','ينبع','الحاسب وتقنية المعلومات','برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أجا العالي للتدريب','حائل','الهندسة','تقنية المساحة','07310702','المساحة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أجا العالي للتدريب','حائل','الهندسة','قسم الانشاءات المدنية','07320201','تقنية الهندسة المدنية ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أجا العالي للتدريب','حائل','الهندسة','برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أضواء السلامة العالي للتدريب','بلقرن','الحاسب الالي','تطبيقات الحاسب المكتبية في السكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أكاديمية الجزيرة العالمية العالي للتدريب ','الرياض','الحاسب وتقنية المعلومات','شبكات الحاسب','07140707','شبكات الحاسب الآلي','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أكاديمية العرب للإطفاء والسلامة والأمن الصناعي العالي للتدريب','جدة','الإطفاء','أخصائي إطفاء','07190407','تقنية السلامة والوقاية من الحريق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أكاديمية العرب للإطفاء والسلامة والأمن الصناعي العالي للتدريب','جدة','السلامة','أخصائي سلامة','07190408','تقنية السلامة ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أكاديمية الموانيِء للدراسات البحرية والتقنية العالي للتدريب ','الدمام','القسم البحري','مراقبي حركة السفن في المواني','10410201','الموانئ والنقل البحري','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد إيتانا العالي للتدريب','المنطفة الشرقية - الدمام','التقنية الآدارية','"إدارة موارد بشرية "','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد إيتانا العالي للتدريب','المنطفة الشرقية - الدمام','الحاسب الآلي والسكرتارية','تطبيقات الحاسب المكتبية والسكرتارية ','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الارتقاء العالي للتدريب ','الدمام',' الحاسب وتقنية المعلومات ',' برمجيات ','06130106','البرمجة والتطبيقات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الارتقاء العالي للتدريب ','الدمام','التقنية الإدارية ',' إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الارتقاء العالي للتدريب ','الدمام','التقنية الإدارية ','تسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الارتقاء العالي للتدريب ','الدمام','العلاقات العامة ','العلاقات العامة ','04140401','العلاقات العامة','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الامداد العالي للتدريب','جدة','الإدارة','التقنية الادارية تخصص الإدارة المكتبية','04132002','إدارة المكاتب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الامداد العالي للتدريب','جدة','الحاسب الالي',' شبكات الحاسب','06120105','تقنية الشبكات ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد البسام العالي للتدريب','الدمام','دبلوم التقنية الإدارية',' إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد البسام العالي للتدريب','الدمام','دبلوم الحاسب وتقنية المعلومات ','شبكات الحاسب','07140707','شبكات الحاسب الآلي','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام / الزهور','التقنية الإدارية','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام / الزهور','التقنية الإدارية','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام / الزهور','التقنية الإدارية','الموارد البشرية','04130201','الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام / الزهور','الحاسب الآلي','الامن السيبراني','06120302','الأمن السيبراني ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام / الزهور','تقنية الغذاء و البيئة','السلامة و الصحة المهنية','10220101','الصحة والسلامة المهنية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام/ الفيحاء','التقنية الإدارية','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام/ الفيحاء','التقنية الإدارية','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام/ الفيحاء','التقنية الإدارية','الموارد البشرية','04130201','الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام/ الفيحاء','الحاسب الآلي','الامن السيبراني','06120302','الأمن السيبراني ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التقنية المميزة العالي للتدريب','الدمام/ الفيحاء','تقنية الغذاء و البيئة','السلامة و الصحة المهنية','10220101','الصحة والسلامة المهنية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التميز الكندي العالي للتدريب','نجران','التقنية الادارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التميز الكندي العالي للتدريب','نجران','التقنية الادارية','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التميز الكندي العالي للتدريب','نجران','الحاسب وتقنية المعلومات','برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الجزيرة التقني العالي للتدريب','المدينة المنورة','الاعمال والإدارة','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الجزيرة التقني العالي للتدريب','المدينة المنورة','التقنية الإدارية',' محاسب','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الجزيرة التقني العالي للتدريب','المدينة المنورة','التقنية الإدارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الجزيرة التقني العالي للتدريب','المدينة المنورة','التقنية الإدارية','التقنية الإدارية تخصص إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الجزيرة التقني العالي للتدريب','المدينة المنورة','التقنية الإدارية','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الجزيرة التقني العالي للتدريب','المدينة المنورة','التقنية الإدارية',' تسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الجزيرة التقني العالي للتدريب','المدينة المنورة','التقنية الإدارية',' محاسب','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الجزيرة التقني العالي للتدريب','المدينة المنورة','الحاسب وتقنية المعلومات','الحاسب وتقنية المعلومات تخصص برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الخليج العالي للتدريب ','خميس مشيط','الأمن السيبراني','الأمن السيبراني','06120302','الأمن السيبراني ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الخليج العالي للتدريب ','خميس مشيط','الحاسب و تقنية المعلومات ','برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الخليج العالي للتدريب ','خميس مشيط','لتقنية الإدارية',' إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الخليج العالي للتدريب ','خميس مشيط','لتقنية الإدارية',' المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد العلوم الإدارية العالي للتدريب','حائل','التقنية الإدارية','التقنية الإدارية تخصص المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد العلوم الإدارية العالي للتدريب','حائل','التقنية الإدارية ','التقنية الإدارية تخصص إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد العلوم الإدارية العالي للتدريب','حائل','التقنية الادارية','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد العلياء العالي للتدريب','جدة','الحاسب الالي','الحاسب وتقنية المعلومات تخصص شبكات الحاسب','06120101','إدارة أنظمة الشبكات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد العلياء العالي للتدريب','جدة','الحاسب الالي','تقنية البرمجة وتطوير الويب','06120108','إدارة شبكات الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد القدرات الإدارية العالي للتدريب','الدمام','ادارة الاعمال و ادارة عامة و محاسبة','العلوم الإدارية','04130303','العلوم الإدارية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد القدرات الإدارية العالي للتدريب','الدمام','الامن السيبراني','الامن السيبراني','06120302','الأمن السيبراني ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد القدرات الإدارية العالي للتدريب','الدمام','الحاسب وتقنية المعلومات','برمجة تطبيقات الويب والهواتف الذكية','06130106','البرمجة والتطبيقات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد القدرات الإدارية العالي للتدريب','الدمام','الذكاء الاصطناعي','التكنولوجيا والذكاء الاصطناعي','06190101','الذكاء الاصطناعي','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد القدرات الإدارية العالي للتدريب','الدمام','امن المعلومات','امن المعلومات','06120301','أمن المعلومات','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد القدرات الإدارية العالي للتدريب','الدمام','موارد بشرية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد اللامحدود العالي للتدريب','تبوك','التقنية الادارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد اللامحدود العالي للتدريب','تبوك','الحاسب الالي','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد اللامحدود العالي للتدريب','تبوك','الحاسب وتقنية المعلومات','برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المجد الجديد العالي للتدريب','حائل','البيئة','السلامة والصحة المهنية','10220101','الصحة والسلامة المهنية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المجد الجديد العالي للتدريب','حائل','البيئة','حماية البيئة','05220101','حماية البيئة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد النجاح العالي للتدريب','جدة','التقنية الإدارية ','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد النجاح العالي للتدريب','جدة','التقنية الإدارية ','التقنية الإدارية تخصص إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد النجاح العالي للتدريب','جدة','التقنية الإدارية ',' الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد النجاح العالي للتدريب','جدة','التقنية الإدارية ','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد النجاح العالي للتدريب','جدة','الموارد البشرية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد النجاح العالي للتدريب','جدة/ مكة','الموارد البشرية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد بصمة خبير العالي للتدريب','مكة المكرمة','خدمات العناية بالشعر و التجميل','تقنية العناية بالشعر','10120103','العناية بالشعر','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد بصمة خبير العالي للتدريب','مكة المكرمة','خدمات العناية بالشعر و التجميل','تقنية العناية بالشعر','10120103','العناية بالشعر','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد بصمة خبير العالي للتدريب','مكة المكرمة','خدمات العناية بالشعر و التجميل','تقنية العناية بالشعر','10120103','العناية بالشعر','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد بصمة خبير العالي للتدريب','مكة المكرمة','خدمات العناية بالشعر و التجميل','تقنية العناية بالشعر','10120103','العناية بالشعر','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تطوير المستقبل العالي للتدريب','حفر الباطن','الحاسب وتقنية المعلومات','الدعم الفني للحاسب','06120203','الدعم الفني للحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تطوير الموارد البشرية العالي للتدريب','الخفجي','التقنية الادارية','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تطوير الموارد البشرية العالي للتدريب','الخفجي','الحاسب وتقنية المعلومات','شبكات الحاسب','06120101','إدارة أنظمة الشبكات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تقنية العصر العالي للتدريب','تبوك','التقنية الادارية','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تقنية العصر العالي للتدريب','تبوك','الحاسب الالي','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تقنية العصر العالي للتدريب','تبوك','الحاسب وتقنية المعلةومات','  برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تقنية العصر العالي للتدريب','تبوك','الحاسب وتقنية المعلةومات',' تخصص برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جازان العالي للتدريب','جازان','التقنية الإدارية',' إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جازان العالي للتدريب','جازان','تقنية الحاسب','شبكات الحاسب','06120105','تقنية الشبكات ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الإقليمي العالي للتدريب','تبوك','التقنية الإدارية','التقنية الإدارية تخصص إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الإقليمي العالي للتدريب','تبوك','التقنية الإدارية','التقنية الإدارية تخصص إدارة وتطوير الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الإقليمي العالي للتدريب','تبوك','التقنية الإدارية','محاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الإقليمي العالي للتدريب','تبوك','تقنية الغذاء والبيئة','تقنية الغذاء والبيئة تخصص السلامة والصحة المهنية ','10220101','الصحة والسلامة المهنية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الدولي العالي للتدريب','جدة','التقنية الإدارية','إدارة وتطوير الموارد البشرية','04130203','تطوير الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الدولي العالي للتدريب','جدة','التقنية الإدارية','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الدولي العالي للتدريب','جدة','التقنية الإدارية','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الدولي العالي للتدريب','جدة','التقنية الإدارية','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الدولي العالي للتدريب','جدة','الحاسب وتقنية المعلومات','برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الدولي العالي للتدريب','جدة','الحاسب وتقنية المعلومات','شبكات الحاسب','06120108','إدارة شبكات الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الدولي العالي للتدريب','مكة المكرمة','التقنية الإدارية','إدارة وتطوير الموارد البشرية','04130203','تطوير الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الدولي العالي للتدريب','مكة المكرمة','التقنية الإدارية','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الدولي العالي للتدريب','مكة المكرمة','الحاسب وتقنية المعلومات','شبكات الحاسب','06120101','إدارة أنظمة الشبكات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد جدة الريادي العالي للتدريب','المدينة المنورة','الحاسب وتقنية المعلومات','شبكات الحاسب','06120101','إدارة أنظمة الشبكات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد حافز العالي للتدريب','نجران','التقنية الإدارية','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد خصائص المعرفة العالي للتدريب','جدة','التقنية الإدارية','إدارة الموارد البشرية ','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد خصائص المعرفة العالي للتدريب','جدة','التقنية الإدارية','العلاقات العامة ','04140401','العلاقات العامة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد خصائص المعرفة العالي للتدريب','جدة','التقنية الإدارية','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد دراسات الخليج العالي للتدريب','محايل عسير','التقنية الإدارية',' إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد دراسات الخليج العالي للتدريب','محايل عسير','الحاسب الآلي','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد دروبي كوم العالي للتدريب ','رفحاء','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رؤية الخليج العالي للتدريب','نجران','التقنية الإدارية',' إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رؤية الخليج العالي للتدريب','نجران','الحاسب وتقنية المعلومات','الأمن السيبراني','06120302','الأمن السيبراني ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رؤية الخليج العالي للتدريب','نجران','الحاسب وتقنية المعلومات',' برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رواد العطاء العالي للتدريب','جدة','التقنية الادارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رواد العطاء العالي للتدريب','جدة','التقنية الادارية','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رواد العطاء العالي للتدريب','جدة','التقنية الادارية','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رواد العطاء العالي للتدريب','جدة','الحاسب وتقنية المعلومات','شبكات الحاسب','06120101','إدارة أنظمة الشبكات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد سلامة المشاريع العالي للتدريب','الرياض','إدارة الخدمات اللوجستية','إدارة الخدمات اللوجستية','04131401','إدارة سلسلة الإمدادات ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد سلامة المشاريع العالي للتدريب','الرياض','السلامة المهنية','السلامة المهنية','10220104','السلامة المهنية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد طيف العربية العالي  للتدريب -نساء','الدمام','التقنية الإدارية','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد فتاة هجر العالي للتدريب','الاحساء','الإدارة','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد فتاة هجر العالي للتدريب','الاحساء','الإدارة','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد فتاة هجر العالي للتدريب','الاحساء','الموارد البشرية','إدارة الموارد البشرية','04130202','إدارة وتنظيم الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد ماز العالي للتدريب','الرياض','التقنية الإدارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد ماز العالي للتدريب','الرياض','الحاسب وتقنية المعلومات','الامن السيبراني','06120302','الأمن السيبراني ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد ماز العالي للتدريب','الرياض','الحاسب وتقنية المعلومات','الذكاء الاصطناعي','06190101','الذكاء الاصطناعي','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مشار العالي للتدريب','حائل','التقنية الإدارية والمالية','تقنيات الأعمال المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مشار العالي للتدريب','حائل','الحاسب وتقنية المعلومات','تقنية البرمجة وتطوير الويب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مشار العالي للتدريب','حائل','تقنية البيئة','تقنية حماية البيئة ','05220101','حماية البيئة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مشار العالي للتدريب','حائل','تقنية الغذاء ','تقنية سلامة الأغذية','07210202','سلامة الأغذية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مهارات العلم العالي للتدريب ','جازان','إدارة أعمال','الأعمال المالية والمصرفية','04120102','الإدارة المالية والمصرفية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مهارات العلم العالي للتدريب ','جازان','إدارة أعمال','الموارد البشرية','04130201','الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مهارات العلم العالي للتدريب ','جازان','الحاسب الآلي','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية بأملج','أملج','الهندسة','التقنية الكهربائية','07130401','تقنية الهندسة الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية بالوجه','الوجه','الهندسة','التقنية الكهربائية','07130401','تقنية الهندسة الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية ببريدة','بريدة','الهندسة','التقنية الكهربائية','07130401','تقنية الهندسة الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية بجازان','جازان','الهندسة','التقنية الكهربائية','07130401','تقنية الهندسة الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية بجازان','جازان','الهندسة','تخطيط وتشغيل الآلات','07150203','تخطيط وتشغيل الآلات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية بجدة','جدة','الهندسة','التقنية الكهربائية','07130401','تقنية الهندسة الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية بمحايل عسير','محايل عسير','الهندسة','التقنية الكهربائية','07130401','تقنية الهندسة الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية لعلوم الطيران بالرياض','الرياض','الهندسة','إلكترونيات الطيران TB2','07160111','إلكترونيات الطائرات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية لعلوم الطيران بالرياض','الرياض','الهندسة','ميكانيكا TB1  ','07160110','ميكانيكا الطائرات ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية لعلوم الطيران بالرياض','الرياض','الهندسة','هياكل الطائرات','07160117','صيانة هياكل طائرات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية لعلوم الطيران بالرياض','الرياض','الهندسة','هياكل و محركات  ','07160117','صيانة هياكل طائرات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية لعلوم الطيران بالرياض','الرياض','الهندسة','إلكترونيات الطيران ','07160111','إلكترونيات الطائرات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية لعلوم الطيران بالرياض','الرياض','الهندسة','اتصالات  ','07160111','إلكترونيات الطائرات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية لعلوم الطيران بالرياض','الرياض','الهندسة','ميكانيكا  ','07160110','ميكانيكا الطائرات ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية العالمية للبنات بالقطيف','القطيف','الإدارة','التأمين','04120501','إدارة المخاطر والتأمين','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالراض','الرياض','التقنية الالكترونية','تقنية الربوتات والذكاء الاصطناعي','07140504','الروبوتات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالرياض','الرياض','الإنتاج الإعلامي','التصميم والطباعة الرقمية','02110203','تصميم المطبوعات والوسائط المتعددة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالرياض','الرياض','التقنية الالكترونية','تقنية الميكاترونيكس','07880203','تقنية الميكاترونكس','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالرياض','الرياض','التقنية الالكترونية','تقنية النظارات','09190201','نظارات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالرياض','الرياض','التقنية الكهربائية','مشغل لوحة التحكم الكهربائية','07130415','مشغل لوحة التحكم الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالرياض','الرياض','التقنية الميكانيكية','الأنظمة الهيدروليكية والنيومات','07150207','أنظمة نيوماتية وهيدروليكية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالرياض','الرياض','الهندسة  المدنية والمعمارية التطبيقية','الهندسة المدنية التطبيقية','07320201','تقنية الهندسة المدنية ','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالرياض','الرياض','الهندسة  المدنية والمعمارية التطبيقية','الهندسة المدنية التطبيقية','07320201','تقنية الهندسة المدنية ','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالرياض','الرياض','تقنية السياحة والضيافة','إدارة الضيافة','10130103','إدارة الضيافة','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية التقنية بالرياض','الرياض','تقنية العمارة والتصميم','التصميم الداخلي','02120101','التصميم الداخلي','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('الكلية العالمية للسياحة والفندقة بالمدينة المنورة','المدينة المنورة','الإدارة','عمليات الحجز وتوفير تذاكر الطيران','04131003','عمليات الطيران','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي التقني لخدمات الكهرباء (SESP)',' الجعيمة/ المنطقة الشرقية ','التقني','صيانة خطوط النقل الهوائية','07130410','صيانة خطوط النقل الهوائي','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي التقني لخدمات الكهرباء (SESP)',' الجعيمة/ المنطقة الشرقية ','التقني','صيانة شبكات التوزيع الكهربائية','07130411','صيانة شبكات التوزيع الكهربائي','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي التقني لخدمات الكهرباء (SESP)',' الجعيمة/ المنطقة الشرقية ','التقنية الكهربائية','كهربائي خطوط أرضية ','07130417','الكابلات الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي التقني لخدمات الكهرباء (SESP)',' بيش/جازان','التقني','صيانة خطوط النقل الهوائية','07130410','صيانة خطوط النقل الهوائي','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي التقني لخدمات الكهرباء (SESP)',' بيش/جازان','التقني','صيانة شبكات التوزيع الكهربائية','07130411','صيانة شبكات التوزيع الكهربائي','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي التقني لخدمات الكهرباء (SESP)',' بيش/جازان','التقنية الكهربائية','كهربائي خطوط أرضية ','07130417','الكابلات الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي التقني لخدمات الكهرباء (SESP)','الرياض','التقني','صيانة خطوط النقل الهوائية','07130410','صيانة خطوط النقل الهوائي','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي التقني لخدمات الكهرباء (SESP)','الرياض','التقني','صيانة شبكات التوزيع الكهربائية','07130411','صيانة شبكات التوزيع الكهربائي','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('المعهد السعودي التقني لخدمات الكهرباء (SESP)','الرياض','التقنية الكهربائية','كهربائي خطوط أرضية ','07130417','الكابلات الكهربائية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('كلية الإتصالات الرياض بنين','الرياض','التقنية الخاصة','التطبيقات المكتبية وصيانة الحاسب للمعوقين سمعيا','06110101','التطبيقات المكتبية وصيانة الحاسب للمعوقين سمعياً','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('كلية الإتصالات الرياض بنين','الرياض','هندسة الحاسب وتقنية المعلومات التطبيقية','الأمن السيبراني','06120302','الأمن السيبراني ','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('كلية الهندسة التطبيقية','الرياض','الهندسة','الالكترونيات','07130425','كهرباء وإلكترونيات','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('كلية الهندسة التطبيقية','الرياض','الهندسة','قوى كهربائية','07130404','تقنية القوى الكهربائية','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('كلية الهندسة التطبيقية','الرياض','الهندسة','ميكاترونيك','07880203','تقنية الميكاترونكس','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('كلية الهندسة التطبيقية','الرياض','الهندسة','إنتاج','07150225','تقنية الإنتاج ','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('كلية الهندسة التطبيقية','الرياض','الهندسة','محركات ومركبات','07160401','المحركات والمركبات','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('كلية الهندسة التطبيقية','الرياض','الهندسة',' هندسة الإتصالات والشبكات','07140802','تقنية هندسة الشبكات والاتصالات ','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('كلية الهندسة التطبيقية','الرياض','الهندسة','هندسة نظم المعلومات ','06130401','نظم المعلومات ','بكالوريوس','656');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أطياف المجتمع العالي للتدريب','جازان',' قسم التقنية الخاصة','التطبيقات المكتبية وصيانة الحاسب لفئة الصم','06110102','التطبيقات المكتبية وصيانة الحاسب لفئة الصم ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أطياف المجتمع العالي للتدريب','جازان','التقنية الادارية','ادارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أطياف المجتمع العالي للتدريب','جازان','قسم التقنية الالكترونية','تقنية الأجهزة الطبية','07190102','الأجهزة الطبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أطياف المجتمع العالي للتدريب','جازان','قسم الحاسب وتقنية المعلومات','الدعم الفني للحاسب','06120203','الدعم الفني للحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أطياف المجتمع العالي للتدريب','جازان','قسم تقنية السياحة والضيافة',' السفر والسياحة','10150104','السفر والسياحة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أكاديمية فتاة المملكة العالي للتدريب','تبوك','التقنية الإدارية',' إدارة مكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أكاديمية فتاة المملكة العالي للتدريب','تبوك','الحاسب وتقنية المعلومات','برمجيات الحاسب','06130101','البرمجة وعلوم الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد أكاديمية فتاة المملكة العالي للتدريب','تبوك','تطبيقات الحاسب المكتبية والسكرتارية','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد افاق القادة العالي للتدريب','الطائف','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الإبتكار المعرفي العالي للتدريب','المدينة المنورة ','تقنية إدارية ','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الإبتكار المعرفي العالي للتدريب','المدينة المنورة ','تقنية إدارية ','إدارة مكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الإبتكار المعرفي العالي للتدريب','المدينة المنورة ','تقنية إدارية ','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التدريب الاداري العالي للتدريب ','الرياض','التقنية الإدارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التدريب الاداري العالي للتدريب ','الرياض','التقنية الإدارية','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد التدريب الاداري العالي للتدريب ','الرياض','التقنية الإدارية','العلوم المصرفية','04120405','العلوم المصرفية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد السمو المتخصص العالي للتدريب','حفر الباطن','التقنية الإدارية','إدارة المستشفيات والخدمات الصحية','04130505','إدارة الخدمات الصحية والمستشفيات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد السمو المتخصص العالي للتدريب','حفر الباطن','التقنية الإدارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد السمو المتخصص العالي للتدريب','حفر الباطن','التقنية الإدارية','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد السمو المتخصص العالي للتدريب','حفر الباطن','التقنية الإدارية','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد السمو المتخصص العالي للتدريب','حفر الباطن','الحاسب الآلي','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد السمو المتخصص العالي للتدريب','حفر الباطن','القانون','القانون','04210101','القانون','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد العصرية العالي للتدريب النسائي','حفر الباطن','إداري',' المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد العصرية العالي للتدريب النسائي','حفر الباطن','إداري',' الموارد البشرية','04130201','الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي ','الخرج','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي ','الخرج','الإدارة','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي ','الرياض','الإدارة',' إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي ','الرياض','الإدارة','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي ','المدينة المنورة','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','الجوف/ سكاكا','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','الجوف/ سكاكا','الإدارة','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','الجوف/ سكاكا','الإدارة','تطبيقات الحاسب المكتبية والسكرتارية ','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','القصيم/ بريدة','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','القصيم/ بريدة','الإدارة','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','المدينة المنورة','الإدارة','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','المدينة المنورة','الإدارة','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','تبوك','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','تبوك','الإدارة','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','تبوك','الإدارة','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','تبوك','الإدارة','الفندقه','10130106','الفندقة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','حائل','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','حائل','الإدارة','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المسانده العالي  ','حائل','الإدارة','تطبيقات الحاسب المكتبية والسكرتارية ','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المفخرة العالي للتدريب','القريات','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد المفخرة العالي للتدريب','القريات','التقنية الإدارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الوطن التقني العالي للتدريب ','المدينة المنورة ','الإدارة ','تسويق ','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الوطن التقني العالي للتدريب ','المدينة المنورة ','الإدارة ','تقنية الموارد البشرية ','04130201','الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد الوطن التقني العالي للتدريب ','المدينة المنورة ','الحاسب الالي  ','شبكات الحاسب ','06120105','تقنية الشبكات ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تعليم الخليج العالي للتدريب','حفرالباطن','الإدارة',' إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تعليم الخليج العالي للتدريب','حفرالباطن','الإدارة','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد تعليم الخليج العالي للتدريب','حفرالباطن','حاسب الي','تقنية شبكات الحاسب ','06120105','تقنية الشبكات ','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رفال العالي للتدريب','حفر الباطن','الإدارة','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رفال العالي للتدريب','حفر الباطن','الإدارة','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رفال العالي للتدريب','حفر الباطن','تقنية المعلومات','شبكات الحاسب ','06120106','دعم أنظمة شبكات الحاسب','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رفال العالي للتدريب','حفر الباطن','التقنية الإدارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رفال العالي للتدريب','حفر الباطن','التقنية الإدارية','المحاسبة','04110101','المحاسبة','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد رفال العالي للتدريب','حفر الباطن','الحاسب وتقنية المعلومات ','شبكات الحاسب ','06120101','إدارة أنظمة الشبكات','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد طيبة الطيبة العالي للتدريب ','المـدينة المـنورة','تقنية ادارية ','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد عالم المفردات العالي للتدريب','حفرالباطن','التقنية الادارية','إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مدار الخليج العالي للتدريب','الدمام','إدارة الأعمال','الإدارة المكتبية','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مدار الخليج العالي للتدريب','الدمام','التقنية الإدارية','التسويق','04140101','التسويق','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مدار الخليج العالي للتدريب','الدمام','التقنية الإدارية ','التأمين التعاوني و التكافلي','04120507','التأمين التكافلي','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد مدار الخليج العالي للتدريب','الدمام','التقنية الإدارية ','التأمين الصحي','04120503','التأمين الصحي','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد نسائم المستقبل العالي للتدريب','حفر الباطن ','الإدارة',' إدارة الموارد البشرية','04130205','إدارة الموارد البشرية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد نسائم المستقبل العالي للتدريب','حفر الباطن ','الإدارة','الادارة المكتبية ','04132001','الإدارة المكتبية','دبلوم متوسط','554');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد نسائم المستقبل العالي للتدريب','حفر الباطن ','الإدارة','تطبيقات الحاسب المكتبية والسكرتارية ','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');
insert into all_tasnif_sa(est, city, division, name_pt, code_sa, name_sa, level, code_level) value('معهد همم العطاء العالي للتدريب','جازان/الدرب','الإدارة','تطبيقات الحاسب المكتبية والسكرتارية','04132004','إدارة مكتبية وسكرتارية ','دبلوم مشارك','454');


update all_tasnif_sa sa set sa.pt_license = (select max(license) from tadreebi_org.establishment e where e.org_name = sa.est);

update all_tasnif_sa sa set sa.pt_deplom_id = (select max(ID) from deplom d where d.deplom = sa.name_pt);


MySQL [tadreebi_deplom]> desc khotta;
+-----------------+-------------+------+-----+---------+-------+
| Field           | Type        | Null | Key | Default | Extra |
+-----------------+-------------+------+-----+---------+-------+
| ID              | int(11)     | NO   | PRI | NULL    |       |
| license         | varchar(30) | NO   | PRI | NULL    |       |
| program_sa_code | varchar(64) | NO   |     | NULL    |       |
| level_sa_code   | varchar(64) | NO   |     | NULL    |       |
+-----------------+-------------+------+-----+---------+-------+


update khotta kh set kh.program_sa_code=(select code_sa from all_tasnif_sa sa where sa.pt_license = kh.license and sa.pt_deplom_id = kh.ID);

update khotta kh set kh.level_sa_code=(select code_level from all_tasnif_sa sa where sa.pt_license = kh.license and sa.pt_deplom_id = kh.ID);