<?php
	$tbf_info = array();
	$tab_info = array();
	$role_info = array();
	include('previleges/table/previleges_sis_table_alert_cat.php');
	include('previleges/table/previleges_sis_table_alert_status.php');
	include('previleges/table/previleges_sis_table_alert_type.php');
	include('previleges/table/previleges_sis_table_alert_user.php');
	include('previleges/table/previleges_sis_table_candidate_status.php');
	include('previleges/table/previleges_sis_table_class_course.php');
	include('previleges/table/previleges_sis_table_class_course_exam.php');
	include('previleges/table/previleges_sis_table_course.php');
	include('previleges/table/previleges_sis_table_courses_config_item.php');
	include('previleges/table/previleges_sis_table_courses_config_template.php');
	include('previleges/table/previleges_sis_table_courses_template.php');
	include('previleges/table/previleges_sis_table_course_sched_item.php');
	include('previleges/table/previleges_sis_table_course_session.php');
	include('previleges/table/previleges_sis_table_cpc_book.php');
	include('previleges/table/previleges_sis_table_cpc_book_category.php');
	include('previleges/table/previleges_sis_table_cpc_book_page.php');
	include('previleges/table/previleges_sis_table_cpc_book_paragraph.php');
	include('previleges/table/previleges_sis_table_cpc_book_type.php');
	include('previleges/table/previleges_sis_table_cpc_course_program.php');
	include('previleges/table/previleges_sis_table_levels_template.php');
	include('previleges/table/previleges_sis_table_level_class.php');
	include('previleges/table/previleges_sis_table_parent_user.php');
	include('previleges/table/previleges_sis_table_period.php');
	include('previleges/table/previleges_sis_table_room.php');
	include('previleges/table/previleges_sis_table_school.php');
	include('previleges/table/previleges_sis_table_school_class.php');
	include('previleges/table/previleges_sis_table_school_condition.php');
	include('previleges/table/previleges_sis_table_school_employee.php');
	include('previleges/table/previleges_sis_table_school_level.php');
	include('previleges/table/previleges_sis_table_school_status.php');
	include('previleges/table/previleges_sis_table_school_type.php');
	include('previleges/table/previleges_sis_table_school_year.php');
	include('previleges/table/previleges_sis_table_sdepartment.php');
	include('previleges/table/previleges_sis_table_session_status.php');
	include('previleges/table/previleges_sis_table_sis_date_system.php');
	include('previleges/table/previleges_sis_table_student.php');
	include('previleges/table/previleges_sis_table_student_file_course.php');
	include('previleges/table/previleges_sis_table_student_session.php');
	include('previleges/table/previleges_sis_table_study_program.php');
	include('previleges/table/previleges_sis_table_wday.php');

 ?>