<?php
class SisCourseSessionAfwStructure
{
    public static function initInstance(&$obj)
    {
        if ($obj instanceof CourseSession) {
            $multiple_key_cols =
                'school_id,levels_template_id,school_level_order,level_class_order,class_name,session_date,session_order';
            $part_cols = 'school_level_order,level_class_order';
            $context_cols = '';
            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD = '';
            $obj->ORDER_BY_FIELDS = $multiple_key_cols;
            $obj->PK_MULTIPLE = '|';
            $obj->PK_MULTIPLE_ARR = explode(',', $multiple_key_cols);
            $obj->UNIQUE_KEY = $obj->PK_MULTIPLE_ARR;
            $obj->editByStep = true;
            $obj->editNbSteps = 3;

            $obj->public_display = true;

            $obj->setContextAndPartitionCols($part_cols, $context_cols);
            $obj->setMultiplePK($multiple_key_cols,$obj->PK_MULTIPLE);
        }
    }

    public static $DB_STRUCTURE = [
        'school_id' => [
            'IMPORTANT' => 'IN',
            'READONLY' => true,
            'SHOW' => true,
            'SEARCH' => true,
            'EDIT' => true,
            'QSEARCH' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'school',
            'SHORTNAME' => 'school',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'RELATION' => 'OneToMany',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'levels_template_id' => [
            'IMPORTANT' => 'IN',
            'SHOW' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'levels_template',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'ANSMODULE' => 'sis',
            'DISPLAY' => '',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'school_level_order' => [
            'IMPORTANT' => 'IN',
            'SHOW' => false,
            'TYPE' => 'INT',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'level_class_order' => [
            'IMPORTANT' => 'IN',
            'SHOW' => false,
            'TYPE' => 'INT',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'level_class_id' => [
            'TYPE' => 'FK',
            'ANSWER' => 'level_class',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'FORMULA',
            'NO-COTE' => true,
            'DEFAUT' => 0,
            'READONLY' => true,
            'DISPLAY' => true,
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'class_name' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'EDIT' => true,
            'TYPE' => 'TEXT',
            'SIZE' => 32,
            'QSEARCH' => true,
            'DISPLAY' => '',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
            'UTF8' => true,
        ],

        'session_date' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'GDAT',
            'FORMAT' => 'LONG',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            // 'DISABLE-READONLY-ADMIN' => true, because part of primary key in partitionned table so avoid to change by interface 
            // but create button to postpone this session to another date so creat enew record in course_session and move all related student_session records
            // by programming
            
            'CSS' => 'width_pct_25',
        ],

        'session_order' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

		'year' => [
            'IMPORTANT' => 'IN',
            'SHOW' => true,
            'DISPLAY' => true,
            'SIZE' => 32,
            'UTF8' => false,
            'TYPE' => 'ENUM',
            'ANSWER' => 'FUNCTION',
            'EDIT' => true,
            'READONLY' => true,
            'MANDATORY' => true,
            'ANSMODULE' => 'sis',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],

                'school_year_id' => [
                    'IMPORTANT' => 'IN',
                    'SEARCH' => true,
                    'QSEARCH' => true,
                    'SHOW' => false,
                    'RETRIEVE' => false,
                    'EDIT' => false,
                    'QEDIT' => false,
                    'UTF8' => false,
                    'TYPE' => 'FK',
                    'ANSWER' => 'school_year',
                    'ANSMODULE' => 'sis',
                    'CATEGORY' => "FORMULA",
                    'RELATION' => 'OneToMany',
                    'SIZE' => 40,
                    'DEFAUT' => 0,
                    'SHORTNAME' => 'sy',
                    'STEP' => 1,
                    'DISPLAY' => true,
                    'DISPLAY-UGROUPS' => '',
                    'EDIT-UGROUPS' => '',
                    'CSS' => 'width_pct_25',
                    'READONLY' => true,
                ],

                'school_class_id' => [
                    'IMPORTANT' => 'IN',
                    'SEARCH' => true,
                    'SHOW' => true,
                    'RETRIEVE' => true,
                    'EDIT' => true,
                    'QEDIT' => false,
                    'SIZE' => 40,
                    'UTF8' => false,
                    'TYPE' => 'FK',
                    'SHORTNAME' => 'sclass',
                    'ANSWER' => 'school_class',
                    'ANSMODULE' => 'sis',
                    'CATEGORY' => 'FORMULA',
                    'RELATION' => 'OneToMany',
                    'DEFAUT' => 0,
                    'DISPLAY' => true,
                    'STEP' => 1,
                    'DISPLAY-UGROUPS' => '',
                    'EDIT-UGROUPS' => '',
                    'READONLY' => true,
                    'CSS' => 'width_pct_25',
                ],

		'semester' => [
            'IMPORTANT' => 'IN',
            'SHOW' => false,
            'SIZE' => 32,
            'UTF8' => false,
            'TYPE' => 'INT',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],		

		'semester_id' => [
            'IMPORTANT' => 'IN',
            'SHOW' => false,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'school_year',
            'ANSMODULE' => 'sis',
            'CATEGORY' => "FORMULA",
            'SIZE' => 40,
            'DEFAUT' => 0,
            'SHORTNAME' => 'sy',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => true,
        ],

        'course_id' => [
            'IMPORTANT' => 'HIGH',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'course',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'RELATION' => 'OneToMany',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
            'NO-COTE' => true,
        ],

        
        'mainwork_book_id' => array('IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => true,  'EDIT' => true,  'QEDIT' => true,  'SIZE' => 40,  'SEARCH-ADMIN' => true,  'SHOW-ADMIN' => true,  'EDIT-ADMIN' => true,  'UTF8' => false,  
                'TYPE' => 'FK',  'ANSWER' => 'cpc_book',  'ANSMODULE' => 'sis',  
                'WHERE' => "book_type_id=1 and course_mfk like '%,§course_id§,%' and (level_class_mfk is null or level_class_mfk ='' or level_class_mfk like '%,§level_class_id§,%')", 
                'DEFAUT' => 0,    'DISPLAY' => true,  'STEP' => 1,  
                'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'READONLY' => true,
                'CSS' => 'width_pct_25',),

        'homework_book_id' => array('IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => true,  'EDIT' => true,  'QEDIT' => true,  'SIZE' => 40,  'SEARCH-ADMIN' => true,  'SHOW-ADMIN' => true,  'EDIT-ADMIN' => true,  'UTF8' => false,  
                'TYPE' => 'FK',  'ANSWER' => 'cpc_book',  'ANSMODULE' => 'sis',  
                'WHERE' => "book_type_id=1 and course_mfk like '%,§course_id§,%' and (level_class_mfk is null or level_class_mfk ='' or level_class_mfk like '%,§level_class_id§,%')", 
                'DEFAUT' => 0,    'DISPLAY' => true,  'STEP' => 1,  
                'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'READONLY' => true,
                'CSS' => 'width_pct_25',),

        'homework2_book_id' => array('IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => true,  'EDIT' => true,  'QEDIT' => true,  'SIZE' => 40,  'SEARCH-ADMIN' => true,  'SHOW-ADMIN' => true,  'EDIT-ADMIN' => true,  'UTF8' => false,  
                'TYPE' => 'FK',  'ANSWER' => 'cpc_book',  'ANSMODULE' => 'sis',  
                'WHERE' => "book_type_id=1 and course_mfk like '%,§course_id§,%' and (level_class_mfk is null or level_class_mfk ='' or level_class_mfk like '%,§level_class_id§,%')", 
                'DEFAUT' => 0,    'DISPLAY' => true,  'STEP' => 1,  
                'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'READONLY' => true,
                'CSS' => 'width_pct_25',),
        

        'session_start_time' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'READONLY' => true,
            'UTF8' => false,
            'TYPE' => 'TIME',
            'ANSWER_METHOD'=>'getPrayerTimeList', 'FORMAT' => 'OBJECT', 
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'session_end_time' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'READONLY' => true,
            
            'UTF8' => false,
            'TYPE' => 'TIME',
            'ANSWER_METHOD'=>'getAfterPrayerTimeList', 'FORMAT' => 'OBJECT', 
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'prof_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'school_employee',
            'ANSMODULE' => 'sis',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'real_start_time' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'TIME',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'real_end_time' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'TIME',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'session_status_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'session_status',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'STEP' => 1,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'session_status_comment' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 255,
            'UTF8' => true,
            'TYPE' => 'TEXT',
            'STEP' => 1,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_75',
        ],

        'course_num' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 32,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'READONLY' => true,
            'READONLY-ADMIN' => true,
            'STEP' => 1,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'attendanceList' => [
            'IMPORTANT' => 'IN',
            'SHOW' => true,
            'EDIT' => true,
            'CATEGORY' => 'FORMULA',
            'SUB-CATEGORY' => 'ITEMS',
            'FORMAT' => 'retrieve',
            'READONLY' => true,
            'TYPE' => 'MFK',
            'ANSWER' => 'student_session',
            'ANSMODULE' => 'sis',
            'NO-SAVE' => true,
            'COLSPAN' => 3,
            'DO-NOT-RETRIEVE-COLS' => [
                'school_id',
                'course_id',
                'session_status_id',
                'levels_template_id',
                'school_level_order',
                'level_class_order',
                'class_name',
                'session_date',
                'session_order',
            ],
            'NEW-TR' => true,
            'NO-LABEL' => false,
            'BUTTONS' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'VIEW-ICON' => false,
            'EDIT-ICON' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'courses' => array(
            'TYPE' => 'FK',  'ANSWER' => 'student_file_course',  'ANSMODULE' => 'sis',  
            'CATEGORY' => 'ITEMS',  'ITEM' => '', 	
            'WHERE' => "school_id=§school_id§ 
                      and year=§year§ 
                      and levels_template_id=§levels_template_id§ 
                      and school_level_order=§school_level_order§ 
                      and level_class_order=§level_class_order§                       
                      and class_name=_utf8§class_name§ 
                      and course_id = §course_id§", 
             'SHOW' => true,  'ICONS' => true,  'DELETE-ICON' => false,  'FORMAT' => 'retrieve',  'EDIT' => false,
               'NO-LABEL' => true,  'BUTTONS' => false,    'DISPLAY' => true,  'STEP' => 3,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_100',),	
/*
        'schoolClassCourse' => [
            'TYPE' => 'FK',
            'ANSWER' => 'school_class_course',
            'ANSMODULE' => 'sis',
            'SHORTNAME' => 'crsp',
            
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'WHERE' =>
                'school_year_id=§school_year_id§ and level_class_id=§level_class_id§ and class_name=_utf8§class_name§ and course_id = §course_id§',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => true,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'NO-LABEL' => true,
            'BUTTONS' => true,
            'FGROUP' => 'crsp',
            'STEP' => 99,
            'OPTIM' => false,
            'READONLY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        	
			'course_plan' => array('IMPORTANT' => 'IN',  'SHOW' => true,  
				'CATEGORY' => 'FORMULA',  'FORMAT' => 'minibox',  
				'TYPE' => 'FK',  'ANSWER' => 'cpc_course_plan',  'ANSMODULE' => 'sis',  'NO-SAVE' => true,  'COLSPAN' => 3,  'STEP' => 3,    'DISPLAY' => true,  
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
				'CSS' => 'width_pct_100',),*/

        'created_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'created_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'GDAT',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'GDAT',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'GDAT',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'active' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'DEFAUT' => 'Y',
            'TYPE' => 'YN',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

'version'                  => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),

'update_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

'delete_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

'display_groups_mfk'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

'sci_id'                        => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 
        'TYPE' => 'FK', 'ANSWER' => 'scenario_item', 'ANSMODULE' => 'pag', 'FGROUP' => 'tech_fields'),

'tech_notes' 	                => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA', "SHOW-ADMIN" => true, 
        'TOKEN_SEP'=>"§", 'READONLY'=>true, "NO-ERROR-CHECK"=>true, 'FGROUP' => 'tech_fields'),				


    ];
}
?>
