<?php
class SisScandidateAfwStructure
{
    public static function initInstance(&$obj)
    {
        if ($obj instanceof Scandidate) {
            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD = '';
            $obj->ORDER_BY_FIELDS = 'school_id,year,level_class_id desc,general desc,distrib desc, candidate_hdate';
            $obj->UNIQUE_KEY = array("school_id","year","student_id");
            $obj->editByStep = true;
            $obj->editNbSteps = 2;                
            // $title = ScandidateTranslator::translateAttribute("scandidate.single","ar");
            $obj->after_save_edit = [
                'class' => 'SchoolYear',
                'formulaAttribute' => 'school_year_id',
                'currmod' => 'sis',
                'currstep' => 5,
            ];
        }
    }

    public static $DB_STRUCTURE = [
        'id' => [
            'SHOW' => false,
            'RETRIEVE' => true,
            'EDIT' => false,
            'TYPE' => 'PK',
            'DISPLAY' => true,
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],


        'student_upload_id' => [
            'SHORTNAME' => 'upload',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'READONLY' => true,
            'UTF8' => false,
            'SIZE' => 40,
            'TYPE' => 'FK',
            'ANSWER' => 'student_upload',
            'ANSMODULE' => 'sis',
            'DEFAUT' => 0,
            'STEP' => 44,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],

        'school_id' => [
            'SHORTNAME' => 'school',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 40,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'school',
            'ANSMODULE' => 'sis',
            'DEFAUT' => 0,
            'QSEARCH' => '',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => true,
        ],

        'levels_template_id' => [
            'IMPORTANT' => 'IN',
            'TYPE' => 'FK',
            'ANSWER' => 'levels_template',
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'school_id.levels_template_id',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'ANSMODULE' => 'sis',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'year' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 32,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            // 'ANSWER' => 'FUNCTION',
            // 'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'school_year_id' => [
            'IMPORTANT' => 'IN',
            'TYPE' => 'FK',
            'ANSWER' => 'school_year',
            'CATEGORY' => 'FORMULA',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'ANSMODULE' => 'sis',
            'DISPLAY' => '',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
            'RELATION' => 'OneToMany', 
        ],

        'candidate_hdate' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 10,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'DATE',
            'FORMAT' => 'HIJRI_UNIT',
            'READONLY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],


        'student_id' => [
            'SHORTNAME' => 'student',
            'SEARCH' => false,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'READONLY' => false,
            'UTF8' => false,
            'SIZE' => 40,
            'TYPE' => 'FK',
            'ANSWER' => 'student',
            'ANSMODULE' => 'sis',
            'DEFAUT' => 0,
            'AUTOCOMPLETE' => true,
            'RELATION' => 'OneToMany', 
            'REQUIRED' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'PLACE-HOLDER' => 'write here the IDN of the student',
            'CSS' => 'width_pct_50',
        ],

        'student_created' => [
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'READONLY' => true,
            'DEFAUT' => 'Y',
            'TYPE' => 'YN',
            'DISPLAY' => '',
            'STEP' => 44,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'full_name' => array('IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => false,  'RETRIEVE' => true,  'EDIT' => false, 
                'SIZE' => 128, 'MAXLENGTH' => 128, 'UTF8' => true,  
				'TYPE' => 'TEXT',  'MINIBOX' => true,    'DISPLAY' => false,  'STEP' => 99, 'QSEARCH' => true, 
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'MANDATORY' => false, 
				'CSS' => 'width_pct_50',),

        'birth_date_en' => array(
					'TYPE' => 'GDAT',  'EDIT' => false,  'QEDIT' => false,  'SHOW' => false,  'SEARCH' => true, 
					'FORMAT' => '',  'MINIBOX' => true,  
					'MANDATORY' => false,    'DISPLAY' => true, 'STEP' => 1,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true, 
					'CSS' => 'width_pct_25',),                


        'start_date_en' => array(
                        'TYPE' => 'GDAT',  'EDIT' => false,  'QEDIT' => false,  'SHOW' => false,  'SEARCH' => true, 
                        'FORMAT' => '',  'MINIBOX' => true,  
                        'MANDATORY' => false,    'DISPLAY' => true, 'STEP' => 1,  
                        'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true, 
                        'CSS' => 'width_pct_25',),                
    

        'age' => array('STEP' => 2,  
					'TYPE' => 'INT',  'EDIT' => true,  
					'CATEGORY' => 'FORMULA',  'SHOW' => true,  'RETRIEVE' => true, 
					'UNIT' => 'سنة', "NO-HZM-UNIT" => true, 'READONLY' => true,  
					'CONSTRAINTS' => ['f-between;2,65'],  
					'MANDATORY' => false,    'DISPLAY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true,  
					'CSS' => 'width_pct_25',),                    

        'level_class_id' => [
            'STEP' => 1,
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 40,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'READONLY' => false,  
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'level_class',
            'ANSMODULE' => 'sis',
            'WHERE' => 'school_level_id in (select slvl.id from §DBPREFIX§sis.school_level slvl 
                                              where slvl.levels_template_id = §levels_template_id§)',
            'QSEARCH' => true,
            'WHERE-SEARCH' => '',
            'DEFAULT' => 0,
            'REQUIRED' => true,
            
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'presence' => array('STEP' => 1,  
						'CATEGORY' => '',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'RETRIEVE' => false, 
						'SEARCH' => true,  'QSEARCH' => false,  'SEARCH-MANDATORY' => true,  'SEARCH-DEFAULT' => true, 
						'QSEARCH' => true,  'DEFAUT' => 1,  'SHOW-ADMIN' => true,  'ROLES' => 6,  
						'MINIBOX' => true,  'DISPLAY' => true,  
						'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
						'CSS' => 'width_pct_25',
						'MANDATORY' => true,  'UTF8' => false,  
						'TYPE' => 'ENUM',  'ANSWER' => "FUNCTION",  
						'RELATION' => 'ManyToOne',  'READONLY' => false, ),

		'school_level_order' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'level_class_id.school_level_id.school_level_order',
        ],

        'level_class_order' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'level_class_id.level_class_order',
        ],

        'level' => array('STEP' => 2,  
						'CATEGORY' => '',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'RETRIEVE' => true, 
						'SEARCH' => true,  'QSEARCH' => false,  'SEARCH-MANDATORY' => true,  'SEARCH-DEFAULT' => true, 
						'QSEARCH' => true,  'DEFAULT' => 1,  'SHOW-ADMIN' => true,  'ROLES' => 6,  
						'MINIBOX' => true,  'DISPLAY' => true,  
						'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
						'CSS' => 'width_pct_25',
						'MANDATORY' => true,  'UTF8' => false,  
						'TYPE' => 'ENUM',  'ANSWER' => "FUNCTION",  
						'RELATION' => 'ManyToOne',  'READONLY' => false, ),	
						
		'eval' => array('STEP' => 2,  
						'CATEGORY' => '',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'RETRIEVE' => true, 
						'SEARCH' => true,  'QSEARCH' => false,  'SEARCH-MANDATORY' => true,  'SEARCH-DEFAULT' => true, 
						'QSEARCH' => true,  'DEFAULT' => 1,  'SHOW-ADMIN' => true,  'ROLES' => 6,  
						'MINIBOX' => true,  'DISPLAY' => true,  
						'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
						'CSS' => 'width_pct_25',
						'MANDATORY' => true,  'UTF8' => false,  
						'TYPE' => 'ENUM',  'ANSWER' => "FUNCTION",  
						'RELATION' => 'ManyToOne',  'READONLY' => false, ),


        'capacity' => array('STEP' => 2,  
						'CATEGORY' => '',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'RETRIEVE' => true, 
						'SEARCH' => true,  'QSEARCH' => false,  'SEARCH-MANDATORY' => true,  'SEARCH-DEFAULT' => true, 
						'QSEARCH' => true,  'DEFAULT' => 4,  'SHOW-ADMIN' => true,  'ROLES' => 6,  
						'MINIBOX' => true,  'DISPLAY' => true,  
						'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
						'CSS' => 'width_pct_25',
						'MANDATORY' => true,  'UTF8' => false,  
						'TYPE' => 'ENUM',  'ANSWER' => "FUNCTION",  
						'RELATION' => 'ManyToOne',  'READONLY' => false, ),


        'moral' => array('STEP' => 2,  
						'CATEGORY' => '',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'RETRIEVE' => true, 
						'SEARCH' => true,  'QSEARCH' => false,  'SEARCH-MANDATORY' => true,  'SEARCH-DEFAULT' => true, 
						'QSEARCH' => true,  'DEFAULT' => 4,  'SHOW-ADMIN' => true,  'ROLES' => 6,  
						'MINIBOX' => true,  'DISPLAY' => true,  
						'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
						'CSS' => 'width_pct_25',
						'MANDATORY' => true,  'UTF8' => false,  
						'TYPE' => 'ENUM',  'ANSWER' => "FUNCTION",  
						'RELATION' => 'ManyToOne',  'READONLY' => false, ),


        'general' => [
                            'IMPORTANT' => 'IN',
                            'SEARCH' => true,
                            'SHOW' => false,
                            'RETRIEVE' => true,
                            'EDIT' => false,
                            'QEDIT' => false,
                            'SEARCH-ADMIN' => true,
                            'SHOW-ADMIN' => true,
                            'EDIT-ADMIN' => true,
                            'UTF8' => false,
                            'TYPE' => 'INT',
                            'DISPLAY' => true,
                            'STEP' => 2,
                            'DISPLAY-UGROUPS' => '',
                            'EDIT-UGROUPS' => '',
                            'READONLY' => true,
                            'CSS' => 'width_pct_25',
                        ],                        


        'distrib' => [
                            'IMPORTANT' => 'IN',
                            'SEARCH' => true,
                            'SHOW' => false,
                            'RETRIEVE' => true,
                            'EDIT' => false,
                            'QEDIT' => false,
                            'SEARCH-ADMIN' => true,
                            'SHOW-ADMIN' => true,
                            'EDIT-ADMIN' => true,
                            'UTF8' => false,
                            'TYPE' => 'INT',
                            'DISPLAY' => true,
                            'STEP' => 2,
                            'DISPLAY-UGROUPS' => '',
                            'EDIT-UGROUPS' => '',
                            'READONLY' => true,
                            'CSS' => 'width_pct_25',
                        ],      

        'class_name' => ['STEP' => 2, 
                        'IMPORTANT' => 'IN',
                        'SEARCH' => true,
                        'EDIT' => true,
                        'TYPE' => 'TEXT',
                        'FROM_LIST' => 'getClassNames',
                        'SIZE' => 32,
                        'QSEARCH' => true,
                        'RETRIEVE' => true,
                        'DISPLAY' => '',
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'UTF8' => true,
                        'CSS' => 'width_pct_25',
                    ],                        

        'candidate_status_id' => [
                'STEP' => 2,
                'IMPORTANT' => 'IN',
                'SEARCH' => true,
                'SHOW' => true,
                'RETRIEVE' => false,
                'EDIT' => true,
                'QEDIT' => false,
                'SIZE' => 40,
                'SEARCH-ADMIN' => true,
                'SHOW-ADMIN' => true,
                'EDIT-ADMIN' => true,
                'UTF8' => false,
                'TYPE' => 'FK',
                'ANSWER' => 'candidate_status',
                'ANSMODULE' => 'sis',
                'DEFAUT' => 1,
                'READONLY' => true,
                'DISPLAY-UGROUPS' => '',
                'EDIT-UGROUPS' => '',
                'CSS' => 'width_pct_25',
            ],            

        
        'comments' => [
            'STEP' => 2,
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 255,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => true,
            'TYPE' => 'TEXT',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_75',
        ],
                        

        
        

        

        'created_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'created_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'GDAT',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'GDAT',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'GDAT',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'active' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'DEFAUT' => 'Y',
            'TYPE' => 'YN',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'version'                  => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),
		
		'update_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
		
		'delete_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
		
		'display_groups_mfk'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
		
		'sci_id'                        => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 
				'TYPE' => 'FK', 'ANSWER' => 'scenario_item', 'ANSMODULE' => 'pag', 'FGROUP' => 'tech_fields'),
		
		'tech_notes' 	                => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA',
                "SHOW-ADMIN" => true, 'EDIT' => false, 'QEDIT' => false,
				'TOKEN_SEP'=>"§", 'READONLY'=>true, "NO-ERROR-CHECK"=>true, 'FGROUP' => 'tech_fields'),
    ];
}
?>
