<?php
class SisSchoolClassAfwStructure
{
    public static function initInstance(&$obj)
    {
        if ($obj instanceof SchoolClass) 
        {

            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD = "";
            $obj->ORDER_BY_FIELDS = "school_year_id, level_class_id, class_name";
            $obj->UNIQUE_KEY = array("school_year_id", "level_class_id", "class_name");
            $obj->editByStep = true;
            $obj->editNbSteps = 13;
        }
	}

    public static $DB_STRUCTURE = [
        'id' => [
            'SHOW' => false,
            'RETRIEVE' => true,
            'EDIT' => false,
            'TYPE' => 'PK',
            'STEP' => 1,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'school_year_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'QSEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'MINIBOX' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'school_year',
            'ANSMODULE' => 'sis',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'SHORTNAME' => 'sy',
            'STEP' => 1,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => true,
            'RELATION' => 'OneToMany',
        ],

        'school_id' => [
            'TYPE' => 'FK',
            'ANSWER' => 'school',
            'ANSMODULE' => 'sis',
            'SHOW' => false,
            'RETRIEVE' => false,
            'EDIT' => false,
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'school_year_id.school_id',
            'SHORTNAME' => 'school',
            'STEP' => 1,
            'DISPLAY' => '',
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
            'RELATION' => 'OneToMany',
        ],

        'levels_template_id' => [
            'IMPORTANT' => 'IN',
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 40,
            'READONLY' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'DEFAUT' => 0,
            'STEP' => 1,
            'ANSWER' => 'levels_template',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'school_year_id.school_id.levels_template_id',
            'DISPLAY' => false,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],
        
        'school_level_order' => [
            'IMPORTANT' => 'IN',
            'TYPE' => 'INT',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'level_class_id.school_level_id.school_level_order',
        ],

        'level_class_order' => [
            'IMPORTANT' => 'IN',
            'TYPE' => 'INT',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'level_class_id.level_class_order',
        ],

        'year' => [
            'TYPE' => 'TEXT',
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'school_year_id.year',
            'STEP' => 1,
            'DISPLAY' => '',
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'level_class_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'UTF8' => false,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'level_class',
            'ANSMODULE' => 'sis',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'WHERE' =>
                'school_level_id in (select slvl.id from c0sis.school_level slvl where slvl.levels_template_id = §levels_template_id§)',
            'QSEARCH' => true,
            /*'WHERE-SEARCH' => "school_level_id in (select slvl.id 
                                                                  from c0sis.school_level slvl 
                                                                      inner join c0sis.school scl on scl.levels_template_id = slvl.levels_template_id
                                                                  where scl.id = '§SUB_CONTEXT_ID§')", */
            'STEP' => 1,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'class_name' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'SIZE' => 1,
            'QEDIT' => true,
            'EDIT' => true,
            'TYPE' => 'TEXT',
            'SIZE' => 32,
            'UTF8' => true,
            'DISPLAY' => true,
            'MINIBOX' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'room_id' => [
            'IMPORTANT' => 'IN',
            'MANDATORY' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'room',
            'ANSMODULE' => 'sis',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'RELATION' => 'OneToOneU',
            'WHERE' => 'school_id = §school_id§',
            'STEP' => 1,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'main_course_id' => array('STEP' => 1,  'SHORTNAME' => 'ctemplate',  'SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  'EDIT' => true,  'QEDIT' => true,  'SIZE' => 40,  'MAXLENGTH' => 32,  'UTF8' => false,  
				'TYPE' => 'FK',  'ANSWER' => 'course',  'ANSMODULE' => 'sis', 
				'CATEGORY' => "SHORTCUT", "SHORTCUT" => "school_year_id.school_id.main_course_id",
				'RELATION' => 'OneToMany',  'READONLY' => true, 'DISPLAY' => true,  
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
				'CSS' => 'width_pct_25',),

        'courses_config_template_id' => array('STEP' => 99,  'SHORTNAME' => 'ctemplate',  'SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  'EDIT' => true,  'QEDIT' => true,  'SIZE' => 40,  'MAXLENGTH' => 32,  'UTF8' => false,  
            'TYPE' => 'FK',  'ANSWER' => 'courses_config_template',  'ANSMODULE' => 'sis', 
            'CATEGORY' => "SHORTCUT", "SHORTCUT" => "school_year_id.school_id.courses_config_template_id",
            'RELATION' => 'OneToMany',  'READONLY' => true, 'DISPLAY' => true,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_25',),

        'prof_id' => array('IMPORTANT' => 'IN',  'RETRIEVE' => true,  'SHOW' => true,  
                'EDIT' => true, 'SIZE' => 40, 
                'CATEGORY' => 'FORMULA', 'READONLY' => true,
				'TYPE' => 'FK',  'ANSWER' => 'school_employee',  'ANSMODULE' => 'sis',  'DEFAUT' => 0,  				 
				'DISPLAY' => true,  'STEP' => 1,  
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
				'CSS' => 'width_pct_25',),

        'wdays_mfk' => array('STEP' => 1,  'SHORTNAME' => 'we',  'SEARCH' => true,  
                'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
                'EDIT' => true,  'QEDIT' => true,  'SIZE' => 32,  'MAXLENGTH' => 32,  'UTF8' => false,  
				'TYPE' => 'MENUM',  'ANSWER' => 'FUNCTION', 'READONLY' => false,  
                'SEARCH-BY-ONE' => false,  'DISPLAY' => true,  
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
				'CSS' => 'width_pct_25',),

        'start_time' => array('IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  'EDIT' => true,  'QEDIT' => true,  'SEARCH-ADMIN' => true,  'SHOW-ADMIN' => true,  'EDIT-ADMIN' => true,  'UTF8' => false,  
				'TYPE' => 'TIME', 'ANSWER_METHOD'=>'getPrayerTimeList', 'FORMAT' => 'OBJECT',  
				'DISPLAY' => true,  'STEP' => 1,  
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
				'CSS' => 'width_pct_25',),

		'end_time' => array('IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  'EDIT' => true,  'QEDIT' => true,  'SEARCH-ADMIN' => true,  'SHOW-ADMIN' => true,  'EDIT-ADMIN' => true,  'UTF8' => false,  
				'TYPE' => 'TIME', 'ANSWER_METHOD'=>'getAfterPrayerTimeList', 'FORMAT' => 'OBJECT',
				'DISPLAY' => true,  'STEP' => 1,  
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
				'CSS' => 'width_pct_25',),                

        'scope_id' => [
            'TYPE' => 'FK',
            'CATEGORY' => 'FORMULA',
            'SHOW' => false,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => true,
            'READONLY' => true,
            'ANSWER' => 'school_scope',
            'ANSMODULE' => 'sis',
            'SHORTNAME' => 'scope',
            'STEP' => 1,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'stdn_nb' => [
            'TYPE' => 'INT',
            'CATEGORY' => 'FORMULA',
            'SHOW' => true,
            'RETRIEVE' => true,
            'FGROUP' => 'stdn',
            'STEP' => 3,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_12',
        ],

        'free_place_nb' => [
            'TYPE' => 'INT',
            'CATEGORY' => 'FORMULA',
            'SHOW' => true,
            'RETRIEVE' => true,
            'FGROUP' => 'stdn',
            'STEP' => 3,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_12',
        ],

       


        'study_program_id' => array('SHORTNAME' => 'config',  'SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true, 
			    'RETRIEVE' => false,  'EDIT' => true,  'QEDIT' => false,  'SIZE' => 40,  'UTF8' => false,  
				'TYPE' => 'FK',  'ANSWER' => 'study_program', 
                'WHERE' => "courses_config_template_id = §courses_config_template_id§ and course_id = §main_course_id§",
                'DEFAUT' => 0,  'MINIBOX' => true,  
				'ANSMODULE' => 'sis',  'STEP' => 1,  
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'RELATION' => 'OneToMany',
				'CSS' => 'width_pct_25',),
        /*
			'cand' => array(
					'TYPE' => 'FK',  'ANSWER' => 'scandidate',  'ANSMODULE' => 'sis',  
					'CATEGORY' => 'ITEMS',  'ITEM' => '',  'ITEM_OPER' => '!=',  
					'WHERE' => "school_id=§school_id§ and year=§year§ and level_class_id=§level_class_id§ and candidate_status_id=1", 
					'SHOW' => true,  'ICONS' => true,  'DELETE-ICON' => false,  'FORMAT' => 'retrieve',  'EDIT' => false,  'NO-LABEL' => true,  'BUTTONS' => true,  'FGROUP' => 'cand',  'STEP' => 2,    'DISPLAY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
					'CSS' => 'width_pct_100',),*/

        'stdn' => [
            'TYPE' => 'FK',
            'ANSWER' => 'student_file',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'WHERE' => 'school_id = §school_id§ and
                        year = §year§ and
                        levels_template_id = §levels_template_id§ and
                        school_level_order = §school_level_order§ and 
                        level_class_order = §level_class_order§ and 
                        class_name = _utf8§class_name§ ',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => true,
            'EDIT-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'NO-LABEL' => true,
            'BUTTONS' => true,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_id',
                1 => 'year',
                2 => 'level_class_id',
                3 => 'class_name',
                4 => 'school_class_id',
                5 => 'idn',
                6 => 'course_program_id',
                7 => 'program_type_id',
                8 => 'status_date',
                9 => 'rate_score',
                10 => 'status_date',
            ],

            'FORCE-RETRIEVE-COLS' => [
                0 => 'age',
            ],

            
            'FGROUP' => 'stdn',
            'STEP' => 3,
            'MINIBOX' => true,
            'ICONS-MINIBOX' => false,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        

        'crsp_nb' => [
            'TYPE' => 'INT',
            'CATEGORY' => 'FORMULA',
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => true,
            'READONLY' => true,
            'CONSTRAINTS' => [0 => 'i-between;1,30'],
            'STEP' => 4,
            'XOPTION_KEY' => 'STATS-COMPUTE',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'ws_req_nb' => [
            'TYPE' => 'INT',
            'CATEGORY' => 'FORMULA',
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => true,
            'READONLY' => true,
            'CONSTRAINTS' => [0 => 'i-between;1,70'],
            'STEP' => 4,
            'XOPTION_KEY' => 'STATS-COMPUTE',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'schoolClassCourseList' => [
            'TYPE' => 'FK',
            'ANSWER' => 'school_class_course',
            'ANSMODULE' => 'sis',
            'SHORTNAME' => 'crsp',
            
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'WHERE' =>
                'school_year_id=§school_year_id§ and level_class_id=§level_class_id§ and class_name=_utf8§class_name§',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'VIEW-ICON' => false,
            'EDIT-ICON' => true, // to edit list of injazet iftiradia
            'FORMAT' => 'retrieve',
            'EDIT' => true,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'NO-LABEL' => true,
            'BUTTONS' => true,
            'FGROUP' => 'crsp',
            'STEP' => 4,
            'OPTIM' => false,
            'READONLY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        /* example from btb
        'FORMAT' => 'crossed', 
        'CROSS_COL'=>'program_title', 
        'CROSSED_FIELD_COL' => 'period_title', 
        'CROSSED_VALUE_COL' =>'price',*/

        'ws_sched_nb' => [
            'TYPE' => 'INT',
            'CATEGORY' => 'FORMULA',
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => true,
            'READONLY' => true,
            'CONSTRAINTS' => [0 => 'i-between;1,70'],
            'STEP' => 4,
            'XOPTION_KEY' => 'STATS-COMPUTE',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'errors_sched_nb' => [
            'TYPE' => 'INT',
            'CATEGORY' => 'FORMULA',
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => true,
            'READONLY' => true,
            'CONSTRAINTS' => [0 => 'i-between;0,0'],
            'STEP' => 4,
            'XOPTION_KEY' => 'STATS-COMPUTE',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'is_ok' => [
            'TYPE' => 'TEXT',
            'CATEGORY' => 'FORMULA',
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => false,
            'QEDIT' => true,
            'READONLY' => true,
            'NO-ERROR-CHECK' => true,
            'STEP' => 4,
            'OPTION_KEY' => 'STATS-COMPUTE',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],


        'sched_1' => [
            'TYPE' => 'FK',
            'ANSWER' => 'course_sched_item',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'ITEM_OPER' => '!=',
            'WHERE' =>
                'school_year_id=§school_year_id§ and level_class_id=§level_class_id§ and class_name=_utf8§class_name§ and wday_id = 1',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'NO-LABEL' => true,
            'BUTTONS' => true,
            'FGROUP' => 'step6',
            'STEP' => 6,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'sched_2' => [
            'TYPE' => 'FK',
            'ANSWER' => 'course_sched_item',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'ITEM_OPER' => '!=',
            'WHERE' =>
                'school_year_id=§school_year_id§ and level_class_id=§level_class_id§ and class_name=_utf8§class_name§ and wday_id = 2',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'BUTTONS' => true,
            'FGROUP' => 'step7',
            'NO-LABEL' => true,
            'STEP' => 7,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'sched_3' => [
            'TYPE' => 'FK',
            'ANSWER' => 'course_sched_item',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'ITEM_OPER' => '!=',
            'WHERE' =>
                'school_year_id=§school_year_id§ and level_class_id=§level_class_id§ and class_name=_utf8§class_name§ and wday_id = 3',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'BUTTONS' => true,
            'FGROUP' => 'step8',
            'STEP' => 8,
            'NO-LABEL' => true,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'sched_4' => [
            'TYPE' => 'FK',
            'ANSWER' => 'course_sched_item',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'ITEM_OPER' => '!=',
            'WHERE' =>
                'school_year_id=§school_year_id§ and level_class_id=§level_class_id§ and class_name=_utf8§class_name§ and wday_id = 4',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'NO-LABEL' => true,
            'BUTTONS' => true,
            'FGROUP' => 'step9',
            'STEP' => 9,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'sched_5' => [
            'TYPE' => 'FK',
            'ANSWER' => 'course_sched_item',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'ITEM_OPER' => '!=',
            'WHERE' =>
                'school_year_id=§school_year_id§ and level_class_id=§level_class_id§ and class_name=_utf8§class_name§ and wday_id = 5',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'NO-LABEL' => true,
            'BUTTONS' => true,
            'FGROUP' => 'step10',
            'STEP' => 10,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'sched_6' => [
            'TYPE' => 'FK',
            'ANSWER' => 'course_sched_item',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'ITEM_OPER' => '!=',
            'WHERE' =>
                'school_year_id=§school_year_id§ and level_class_id=§level_class_id§ and class_name=_utf8§class_name§ and wday_id = 6',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'NO-LABEL' => true,
            'BUTTONS' => true,
            'FGROUP' => 'step11',
            'STEP' => 11,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'sched_7' => [
            'TYPE' => 'FK',
            'ANSWER' => 'course_sched_item',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'ITEM_OPER' => '!=',
            'WHERE' =>
                'school_year_id=§school_year_id§ and level_class_id=§level_class_id§ and class_name=_utf8§class_name§ and wday_id = 7',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'NO-LABEL' => true,
            'BUTTONS' => true,
            'FGROUP' => 'step12',
            'STEP' => 12,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],
                'start_near_date' => [
                    'TYPE' => 'GDAT',
                    'STEP' => 99,
                    'CATEGORY' => 'FORMULA',
                ],

                'end_near_date' => [
                    'TYPE' => 'GDAT',
                    'STEP' => 99,
                    'CATEGORY' => 'FORMULA',
                ],

        'courseSessionList' => [
            'TYPE' => 'FK',
            'ANSWER' => 'course_session',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'WHERE' =>
                'school_id=§school_id§ and 
                 levels_template_id=§levels_template_id§ and 
                 school_level_order=§school_level_order§ and 
                 level_class_order=§level_class_order§ and 
                 class_name=_utf8§class_name§ and 
                 session_date between §start_near_date§ and §end_near_date§',
            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'NO-LABEL' => false,
            'BUTTONS' => true,
            'STEP' => 13,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_year_id',
                1 => 'level_class_id',
                2 => 'class_name',
            ],
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'created_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'created_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'DATETIME',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'DATETIME',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'DATETIME',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'active' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'DEFAUT' => 'Y',
            'TYPE' => 'YN',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

'version'                  => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),

'update_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

'delete_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

'display_groups_mfk'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

'sci_id'                        => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 
        'TYPE' => 'FK', 'ANSWER' => 'scenario_item', 'ANSMODULE' => 'pag', 'FGROUP' => 'tech_fields'),

'tech_notes' 	                => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA', "SHOW-ADMIN" => true, 
        'TOKEN_SEP'=>"§", 'READONLY'=>true, "NO-ERROR-CHECK"=>true, 'FGROUP' => 'tech_fields'),				



    ];
}
?>
