<?php
class SisStudentFileAfwStructure
{
    public static function initInstance(&$obj)
    {
        if($obj instanceof StudentFile)
        {

            $multiple_key_cols = "student_id,school_id,year,levels_template_id,school_level_order,level_class_order";
            $part_cols = "student_id";
            $context_cols = "";

            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            // $obj->HIDE_DISPLAY_MODE = true;
            // $obj->hideQeditCommonFields = true;
            $obj->DISPLAY_FIELD = "";
            $obj->ORDER_BY_FIELDS = $multiple_key_cols; // "firstname, f_firstname, lastname,".
            $obj->PK_MULTIPLE = "|";
            $obj->PK_MULTIPLE_ARR = explode(",",$multiple_key_cols);
            $obj->UNIQUE_KEY = $obj->PK_MULTIPLE_ARR;
            $obj->editByStep = true;
            $obj->editNbSteps = 8;
            
            $obj->setContextAndPartitionCols($part_cols, $context_cols);
            $obj->setMultiplePK($multiple_key_cols,$obj->PK_MULTIPLE);

        }        
    }
    public static $DB_STRUCTURE = [

        'school_id' => ['STEP' => 1, 
            'IMPORTANT' => 'high',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 40,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'school',
            'ANSMODULE' => 'sis',
            'MANDATORY' => true,
            //'PILLAR' => true,
            //'WHERE' => "id = '§SUB_CONTEXT_ID§'",
            'DEFAUT' => 0,
            'DISPLAY' => true,
            'READONLY' => true,
            'DISPLAY-UGROUPS' => '',
            'RELATION' => 'OneToMany',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],

        'year' => ['STEP' => 1, 
            'IMPORTANT' => 'high',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'QSEARCH' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            // 'ANSWER' => 'FUNCTION',
            'READONLY' => true,
            'MANDATORY' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],

        'levels_template_id' => ['STEP' => 1, 
            'IMPORTANT' => 'high',
            'SEARCH' => true,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'levels_template',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'school_level_order' => ['STEP' => 1, 
            'IMPORTANT' => 'high',
            'SEARCH' => true,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

                            'is_qualif_diploma' => array(
                                'TYPE' => 'INT',  
                                'CATEGORY' => 'FORMULA',  'SEARCH-BY-ONE' => '',  'DISPLAY' => '',  'STEP' => 99,
                                'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 				),

                            'is_diploma' => array(
                                'TYPE' => 'INT',  
                                'CATEGORY' => 'FORMULA',  'SEARCH-BY-ONE' => '',  'DISPLAY' => '',  'STEP' => 99,
                                'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 				),

        'level_class_order' => ['STEP' => 1, 
            'IMPORTANT' => 'high',
            'SEARCH' => true,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

                            'level_class_id' => ['STEP' => 1, 
                                'TYPE' => 'FK',
                                'ANSWER' => 'level_class',
                                'ANSMODULE' => 'sis',
                                'CATEGORY' => 'FORMULA',
                                'NO-COTE' => true,
                                'DEFAUT' => 0,
                                'READONLY' => true,
                                'DISPLAY' => true,
                                'DISPLAY-UGROUPS' => '',
                                'EDIT-UGROUPS' => '',
                                'CSS' => 'width_pct_100',
                            ],

        'class_name' => ['STEP' => 1, 
            'IMPORTANT' => 'high',
            'SEARCH' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'TYPE' => 'TEXT',
            'FROM_LIST' => 'getClassNames',
            'SIZE' => 32,
            'QSEARCH' => true,
            'DISPLAY' => '',
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'UTF8' => true,
            'CSS' => 'width_pct_25',
        ],

        'semester' => ['STEP' => 99, 
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'MANDATORY' => false,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],

                'school_class_id' => ['STEP' => 4, 
                    'IMPORTANT' => 'IN',
                    'SEARCH' => true,
                    'SHOW' => false,
                    'RETRIEVE' => false,
                    'EDIT' => false,
                    'QEDIT' => false,
                    'SIZE' => 40,
                    'UTF8' => false,
                    'TYPE' => 'FK',
                    'SHORTNAME' => 'sclass',
                    'ANSWER' => 'school_class',
                    'ANSMODULE' => 'sis',
                    'CATEGORY' => 'FORMULA',
                    'DEFAUT' => 0,
                    'RELATION' => 'OneToMany',
                    
                    'DISPLAY-UGROUPS' => '',
                    'EDIT-UGROUPS' => '',
                    'READONLY' => true,
                    'CSS' => 'width_pct_25',
                ],



        'idn_type_id' => array('STEP' => 1,  'IMPORTANT' => 'high',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  'EDIT' => true, 
            'QEDIT' => false,  'SIZE' => 40,  'UTF8' => false, 'MANDATORY' => true,  
            'TYPE' => 'FK',  'ANSWER' => 'idn_type',  'ANSMODULE' => 'pag',  'DEFAUT' => 0,  'MINIBOX' => true,    'DISPLAY' => true,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_25',),

        'idn' => array('STEP' => 1,  'IMPORTANT' => 'high',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false, 
            'EDIT' => true,  'QEDIT' => false,
            'SIZE' => 20,  'UTF8' => true, 'MANDATORY' => true, 'QSEARCH' => true,  'TEXT-SEARCHABLE-SEPARATED'=>true,
            'TYPE' => 'TEXT',  'FORMAT' => 'SA-IDN',  'MINIBOX' => true,    'DISPLAY' => true,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_25',),


        'genre_id' => array('STEP' => 2,  
            'CATEGORY' => '',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'RETRIEVE' => false, 
            'SEARCH' => true,  'QSEARCH' => false,  'SEARCH-MANDATORY' => true,  'SEARCH-DEFAULT' => true, 
            'QSEARCH' => true,  'DEFAUT' => 1,  'SHOW-ADMIN' => true,  'ROLES' => 6,  
            'MINIBOX' => true,  'DISPLAY' => true,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_25',
            'MANDATORY' => true,  'UTF8' => false,  
            'TYPE' => 'ENUM',  'ANSWER' => "FUNCTION",  
            'RELATION' => 'ManyToOne',  'READONLY' => false, ),

                                    

        'firstname' => array('STEP' => 2, 'IMPORTANT' => 'high',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => true,  
            'EDIT' => true,  'QEDIT' => true, 'READONLY' => false, 'SIZE' => 30,  'UTF8' => true,  
            'TYPE' => 'TEXT',  'MINIBOX' => true,    'DISPLAY' => true,  'QSEARCH' => true, 
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'MANDATORY' => true, 'EXCEL' => true,
            'CSS' => 'width_pct_25',),

        'f_firstname' => array('STEP' => 2, 'IMPORTANT' => 'small',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => true,  
            'EDIT' => true,  'QEDIT' => true,  'SIZE' => 30,  'UTF8' => true, 'MANDATORY' => true, 
            'TYPE' => 'TEXT',  'MINIBOX' => true, 'READONLY' => false, 'DISPLAY' => true, 'QSEARCH' => true,
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'EXCEL' => true,
            'CSS' => 'width_pct_25',),

        'lastname' => array('STEP' => 2, 'IMPORTANT' => 'medium',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => true, 
            'EDIT' => true,  'QEDIT' => true, 'READONLY' => false,  'SIZE' => 30,  'UTF8' => true,  
            'TYPE' => 'TEXT',  'MINIBOX' => true,    'DISPLAY' => true,  'QSEARCH' => true,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'MANDATORY' => true, 'EXCEL' => true,
            'CSS' => 'width_pct_25',),

        'mobile' => array('STEP' => 2, 'IMPORTANT' => 'medium',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => true,  
            'EDIT' => true,  'QEDIT' => true,  'SIZE' => 20,  'UTF8' => true,  
            'TYPE' => 'TEXT',  'MINIBOX' => true,    'DISPLAY' => true,  'QSEARCH' => true,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'MANDATORY' => true,  
            'CSS' => 'width_pct_25',),

        'country_id' => array('STEP' => 2, 'IMPORTANT' => 'IN',  'SEARCH' => true, 'SHOW' => true,  'RETRIEVE' => false,  
            'EDIT' => true,  'QEDIT' => false,  'SIZE' => 40,  'UTF8' => false,  
            'TYPE' => 'FK',  'ANSWER' => 'country',  'DEFAUT' => 0,  'ANSMODULE' => 'pag',  'MINIBOX' => true,    'DISPLAY' => true,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_25',),            

        'birth_date' => array('STEP' => 2, 
            'TYPE' => 'DATE',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  
            'SEARCH' => true,  'FORMAT' => 'CONVERT_NASRANI',  'MINIBOX' => true,  
            'MANDATORY' => false,    'RETRIEVE' => false,   
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true, 
            'CSS' => 'width_pct_25',),

        'birth_date_en' => array('STEP' => 2, 
                'TYPE' => 'GDAT',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'SEARCH' => true, 
                'FORMAT' => '',  'MINIBOX' => true,  
                'MANDATORY' => false,    'DISPLAY' => true,   
                'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true, 
                'CSS' => 'width_pct_25',),
                
        'parent_mobile' => array('STEP' => 2, 'IMPORTANT' => 'high',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => true,  
            'EDIT' => true,  'QEDIT' => false,  'SIZE' => 20,  'UTF8' => true,  
            'TYPE' => 'TEXT',  'MINIBOX' => true,    'DISPLAY' => true,  'STEP' => 2,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'MANDATORY' => true,
            'CSS' => 'width_pct_25',),

        'parent_idn_type_id' => array('STEP' => 2,  'IMPORTANT' => 'high',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  
            'EDIT' => true,  'QEDIT' => false,  'SIZE' => 40,  'UTF8' => false,  
            'TYPE' => 'FK',  'ANSWER' => 'idn_type',  'ANSMODULE' => 'pag',  'DEFAUT' => 0,  'MINIBOX' => true,    'DISPLAY' => false,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'MANDATORY' => true,
            'CSS' => 'width_pct_25',),

        'parent_idn' => array('STEP' => 2, 'IMPORTANT' => 'medium',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  
            'EDIT' => true,  'QEDIT' => false,  'SIZE' => 20,  'UTF8' => true,  
            'TYPE' => 'TEXT',  'FORMAT' => 'SA-IDN',  'MINIBOX' => true,    'DISPLAY' => true,    
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'MANDATORY' => true,
            'CSS' => 'width_pct_25',),
        

        'mother_mobile' => array('STEP' => 2, 'IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  
                        'EDIT' => true,  'QEDIT' => false,  'SIZE' => 20,  'UTF8' => true,  
                        'TYPE' => 'TEXT',  'MINIBOX' => true,    'DISPLAY' => true,    
                        'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
                        'CSS' => 'width_pct_25',),
        
        'mother_idn_type_id' => array('STEP' => 2, 'IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false, 
                        'EDIT' => true,  'QEDIT' => false,  'SIZE' => 40,  'UTF8' => false,  
                        'TYPE' => 'FK',  'ANSWER' => 'idn_type',  'ANSMODULE' => 'pag',  'DEFAUT' => 0,  'MINIBOX' => true,    'DISPLAY' => false,  
                        'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
                        'CSS' => 'width_pct_25',),
        
        'mother_idn' => array('STEP' => 2, 'IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false, 
                        'EDIT' => true,  'QEDIT' => false,  'SIZE' => 20,  'UTF8' => true,  
                        'TYPE' => 'TEXT',  'FORMAT' => 'SA-IDN',  'MINIBOX' => true,    'DISPLAY' => true,   
                        'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
                        'CSS' => 'width_pct_25',),							

        'student_id' => ['STEP' => 3, 
                    'IMPORTANT' => 'IN',
                    'SEARCH' => false,
                    'SHOW' => true,
                    'RETRIEVE' => false,
                    'EDIT' => false,
                    'QEDIT' => false,
                    'SIZE' => 40,
                    'TYPE' => 'FK',
                    'ANSWER' => 'student',
                    'ANSMODULE' => 'sis',
                    'MANDATORY' => true,
                    'RELATION' => 'OneToMany',
                    // 'PILLAR' => false,
                    'DEFAUT' => 0,
                    'AUTOCOMPLETE' => false,
                    'WHERE' =>
                        'id in (select student_id from c0sis.scandidate where school_id=§school_id§ and year=§year§ and level_class_id=§level_class_id§)', // id not in (select student_id from c0sis.student_file sf1 where sf1.student_id = §student_id§ or sf1.year = §year§ )
                    'DISPLAY' => true,
                    'READONLY' => true,
                    'DISPLAY-UGROUPS' => '',
                    'EDIT-UGROUPS' => '',
                    'ERROR-CHECK' => true,
                    'CSS' => 'width_pct_25',
                ], 
                
        'age' => array('STEP' => 3,  
                'TYPE' => 'INT',  'EDIT' => true, 'QEDIT' => false,  
                'CATEGORY' => 'FORMULA',  'SHOW' => true,  'RETRIEVE' => false, 
                'UNIT' => 'سنة', "NO-HZM-UNIT" => true, 'READONLY' => true,  
                'CONSTRAINTS' => ['f-between;2,65'],  
                'MANDATORY' => false,    'DISPLAY' => true,  
                'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true,  
                'CSS' => 'width_pct_25',),				

        'level' => array('STEP' => 3,  
                    'CATEGORY' => '',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'RETRIEVE' => false, 
                    'SEARCH' => true,  'QSEARCH' => false,  'SEARCH-MANDATORY' => true,  'SEARCH-DEFAULT' => true, 
                    'DEFAUT' => 1,  'SHOW-ADMIN' => true,  'ROLES' => 6,  
                    'MINIBOX' => true,  'DISPLAY' => true,  
                    'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
                    'CSS' => 'width_pct_25',
                    'MANDATORY' => true,  'UTF8' => false,  
                    'TYPE' => 'ENUM',  'ANSWER' => "FUNCTION",  
                    'RELATION' => 'ManyToOne',  'READONLY' => false, ),	
                    
        'eval' => array('STEP' => 3,  
                    'CATEGORY' => '',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'RETRIEVE' => false, 
                    'SEARCH' => true,  'QSEARCH' => false,  'SEARCH-MANDATORY' => true,  'SEARCH-DEFAULT' => true, 
                    'DEFAUT' => 1,  'SHOW-ADMIN' => true,  'ROLES' => 6,  
                    'MINIBOX' => true,  'DISPLAY' => true,  
                    'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
                    'CSS' => 'width_pct_25',
                    'MANDATORY' => true,  'UTF8' => false,  
                    'TYPE' => 'ENUM',  'ANSWER' => "FUNCTION",  
                    'RELATION' => 'ManyToOne',  'READONLY' => false, ),	                
        
        

        'reg_date' => array(
            'TYPE' => 'DATE',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'SEARCH' => true,  
            'FORMAT' => 'CONVERT_NASRANI',  'MINIBOX' => true,  'RETRIEVE' => false,
            'MANDATORY' => false,  'READONLY' => true,    'DISPLAY' => true,  'STEP' => 3, 'EXCEL' => true, 
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true, 
            'CSS' => 'width_pct_25',),	

        

        /*
        'idn' => array('CATEGORY' => 'SHORTCUT',  'SHORTCUT' => 'student_id.idn',  'SHOW' => true,  'RETRIEVE' => false,  'EDIT' => true,  'QEDIT' => false,
			    'SIZE' => 20,  
				'TYPE' => 'TEXT',  'FORMAT' => 'SA-IDN', 'STEP' => 1,  'READONLY' => true,
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
				'CSS' => 'width_pct_25',),*/

        'student_num' => ['STEP' => 3, 
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'QSEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 10,
            'UTF8' => true,
            'TYPE' => 'TEXT',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],        


        'address' => array('FGROUP' => 'address',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  
            'EDIT' => true,  'QEDIT' => false,  'SIZE' => 128,  'UTF8' => true,  
            'TYPE' => 'TEXT',    'DISPLAY' => true,  'STEP' => 2,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_25',),

        'cp' => array('FGROUP' => 'address',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  
            'EDIT' => true,  'QEDIT' => false,  'SIZE' => 20,  'UTF8' => true,  
            'TYPE' => 'TEXT',    'DISPLAY' => true,  'STEP' => 2,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_25',),

        'city_id' => array('FGROUP' => 'address',  'SEARCH' => true,  'QSEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false, 
            'EDIT' => true,  'QEDIT' => false,  'SIZE' => 40,  'UTF8' => false,  
            'TYPE' => 'FK',  'ANSWER' => 'city',  'DEFAUT' => 0,  'ANSMODULE' => 'pag', 
            'MINIBOX' => true,  'SEARCH-BY-ONE' => false,  'DISPLAY' => true, 'AUTOCOMPLETE' => true,
            'STEP' => 2,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_25',),

        'quarter' => array('FGROUP' => 'address',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  'EDIT' => true, 
            'QEDIT' => false,  'SIZE' => 40,  'UTF8' => true,  
            'TYPE' => 'TEXT',    'DISPLAY' => true,  'STEP' => 2,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_25',),

        'email' => array('FGROUP' => 'address',  'SEARCH' => false,  'SHOW' => true,  'RETRIEVE' => false,  'EDIT' => true,  
            'QEDIT' => false,  'SIZE' => 128,  'SEARCH-ADMIN' => true,  'SHOW-ADMIN' => true,  'EDIT-ADMIN' => true,  'UTF8' => true,  
            'TYPE' => 'TEXT',  'MINIBOX' => true,    'DISPLAY' => true,  'STEP' => 2,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_75',),

        

        'studentList' => [
            'STEP' => 4,
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'school_class_id.stdn',
            'SHORTCUT-CATEGORY' => 'FORMULA',
            'SUB-CATEGORY' => 'ITEMS',
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'FORMAT' => 'retrieve',
            'READONLY' => true,
            'TYPE' => 'MFK',
            'ANSWER' => 'student_file',
            'ANSMODULE' => 'sis',
            'NO-SAVE' => true,
            'COLSPAN' => 3,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_id',
                1 => 'year',
                2 => 'level_class_id',
                3 => 'class_name',
                4 => 'school_class_id',
                5 => 'idn_type_id',
                6 => 'course_program_id',
                7 => 'program_type_id',
                8 => 'status_date',
                9 => 'rate_score',
                10 => 'status_date',
            ],
            'NEW-TR' => true,
            'NO-LABEL' => false,
            'BUTTONS' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'VIEW-ICON' => true,
            'EDIT-ICON' => false,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],


        'course_program_id' => ['STEP' => 5, 
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 40,
            'QSEARCH' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_course_program',
            'ANSWERMODULE' => 'sis',
            'AUTOCOMPLETE-SEARCH' => true,
            'AUTOCOMPLETE' => true,
            'CSS' => 'width_pct_25',
            'DEFAULT' => 0,
        ],

                    'course_program_school_id' => array('CATEGORY' => 'FORMULA', 
                            'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  'EDIT' => true, 'EXCEL' => true,
                            'QEDIT' => false,  'UTF8' => false,  
                            'TYPE' => 'FK',  'ANSWER' => 'course_program_school',  'ANSMODULE' => 'sis',  'SIZE' => 40,  
                            'DEFAUT' => 0,    'DISPLAY' => true,  'STEP' => 5,  
                            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
                            'CSS' => 'width_pct_50',  'READONLY' => true,),

                    'program_type_id' => array('CATEGORY' => 'SHORTCUT', 'SHORTCUT'=> 'course_program_id.program_type_id',
                            'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => false,  'EDIT' => true, 'EXCEL' => true,
                            'QEDIT' => false,  'UTF8' => false,  
                                'TYPE' => 'FK',  'ANSWER' => 'program_type',  'ANSMODULE' => 'sis',  'SIZE' => 40,  
                                'DEFAUT' => 0,    'DISPLAY' => true,  'STEP' => 5,  
                                'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
                                'CSS' => 'width_pct_25',  'READONLY' => true,),

                           
                    
                    

            'course_program_name_ar' => array('STEP' => 5,  'SEARCH' => true,  'SHOW' => false,  'EXCEL' => true,  
					'EDIT' => false,  'QEDIT' => false,  'SIZE' => 32, 'UTF8' => true,   					
					'CATEGORY' => 'SHORTCUT', 'SHORTCUT' => 'course_program_id.course_program_name_ar',
					'TYPE' => 'TEXT',    'READONLY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
					'CSS' => 'width_pct_50',),					

				
					
			'duration' => array('STEP' => 5,  'SEARCH' => true,    'SHOW' => true,  'AUDIT' => false,  
					'EXCEL' => true,  'EDIT' => true,  'QEDIT' => false,  'SIZE' => 40,  'MAXLENGTH' => 32,  'UTF8' => false,  
					'CATEGORY' => 'SHORTCUT', 'SHORTCUT' => 'course_program_id.duration',
					'TYPE' => 'INT', /*'UNIT' => 'يوم', because readonly and unit will be in text directely */
					'READONLY' => true,    'DISPLAY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
					'CSS' => 'width_pct_25',),		
					
					
			'ref_num' => array('STEP' => 10, 'SEARCH' => true,    'SHOW' => true,  'AUDIT' => false,  
					'EXCEL' => true,  'EDIT' => true,  'QEDIT' => false,  'SIZE' => 32,  
					'MAXLENGTH' => 32,  'MIN-SIZE' => 5,  'CHAR_TEMPLATE' => '',  'UTF8' => false,  
					'CATEGORY' => 'SHORTCUT', 'SHORTCUT' => 'school_id.ref_num',
					'TYPE' => 'TEXT',  'READONLY' => false, 'DISPLAY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
					'CSS' => 'width_pct_25',),		
					
			'school_name_ar' => array('STEP' => 10,  'SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false, 
					'EXCEL' => true,  'EDIT' => true,  'QEDIT' => false,  'SIZE' => 48,  'MAXLENGTH' => 48,  
					'MIN-SIZE' => 5,  'CHAR_TEMPLATE' => 'ARABIC-CHARS,SPACE',  'UTF8' => true,  
					'CATEGORY' => 'SHORTCUT', 'SHORTCUT' => 'school_id.school_name_ar',
					'TYPE' => 'TEXT',  'READONLY' => false,  'SEARCH-BY-ONE' => false,  'DISPLAY' => true,  					
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'MANDATORY' => true, 
					'CSS' => 'width_pct_25',),
					
			'address' => array('STEP' => 10,  'SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  
					'EXCEL' => true,  'EDIT' => true,  'QEDIT' => false,  'SIZE' => 128,  'MAXLENGTH' => 32,  'UTF8' => true,  
					'CATEGORY' => 'SHORTCUT', 'SHORTCUT' => 'school_id.address',
					'TYPE' => 'TEXT',  'READONLY' => false,  'SEARCH-BY-ONE' => false,  'DISPLAY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
					'CSS' => 'width_pct_25',),
	
/*
			'region_id' => array('STEP' => 10,  'IMPORTANT' => 'IN',  'SEARCH' => true, 'QSEARCH' => true, 'SHOW' => true,  
					'EXCEL' => true,  'EDIT' => true,  'QEDIT' => false,  'SEARCH-ADMIN' => true,  
					'SHOW-ADMIN' => true,  'EDIT-ADMIN' => true,  'UTF8' => false,  
					'CATEGORY' => 'SHORTCUT', 'SHORTCUT' => 'school_id.city_id.region_id',
					'TYPE' => 'FK',  'ANSWER' => 'region',  'ANSMODULE' => 'pag',  'SIZE' => 40, 
                    'DEFAUT' => 0,    'DISPLAY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
					),					

            'city_id' => array('STEP' => 10,  'SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  
					'EXCEL' => true,  'EDIT' => true,  'QEDIT' => false,  'SIZE' => 40,  'MAXLENGTH' => 32,  'UTF8' => false,  
					'CATEGORY' => 'SHORTCUT', 'SHORTCUT' => 'school_id.city_id',
					'TYPE' => 'FK',  'ANSWER' => 'city',  'ANSMODULE' => 'pag',  'AUTOCOMPLETE' => true,  
					'RELATION' => 'ManyToOne',  'READONLY' => false,  'SEARCH-BY-ONE' => false,  'DISPLAY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
					'CSS' => 'width_pct_25',),
*/
	
			'quarter' => array('STEP' => 10,  'SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  
					'EXCEL' => true,  'EDIT' => true,  'QEDIT' => false,  'SIZE' => 32,  'MAXLENGTH' => 32,  'UTF8' => true,  
					'CATEGORY' => 'SHORTCUT', 'SHORTCUT' => 'school_id.quarter',
					'TYPE' => 'TEXT',  'READONLY' => false,  'SEARCH-BY-ONE' => false,  'DISPLAY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
					'CSS' => 'width_pct_25',),	                    

        'student_file_title' => [
            'FGROUP' => 'result',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 80,
            'UTF8' => true,
            'TYPE' => 'TEXT',
            'STEP' => 6,
            'READONLY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],

        'student_file_status_id' => [
            'FGROUP' => 'result',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'QSEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 40,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'student_file_status',
            'ANSMODULE' => 'sis',
            'DEFAUT' => 1,
            'STEP' => 6,
            'DISPLAY' => true,
            'READONLY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        

        'status_date' => [
            'FGROUP' => 'result',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EXCEL' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 10,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'GDAT',
            /*'FORMAT' => 'CONVERT_HIJRI',
            'IF-SEEMS-HIJRI-KEEP' => true,*/
            'STEP' => 6,
            'DISPLAY' => true,
            'READONLY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'rate_score' => [
            'FGROUP' => 'result',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 10,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'FLOAT', 'FORMAT' => '*.2',
            'STEP' => 6,
            'DISPLAY' => true,
            'READONLY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'final_rating_id' => [
            'FGROUP' => 'result',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'SIZE' => 40,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'rating',
            'ANSMODULE' => 'sis',
            'DEFAUT' => 0,
            'READONLY' => true,
            'STEP' => 6,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'paid' => [
            'FGROUP' => 'payment',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'YN',
            'DEFAULT' => 'N',
            'STEP' => 6,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'paid_amount' => [
            'FGROUP' => 'payment',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'AMNT',
            'STEP' => 6,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'paid_hdate' => [
            'FGROUP' => 'payment',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 10,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'DATE',
            'FORMAT' => 'CONVERT_NASRANI',
            'STEP' => 6,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'paid_comment' => [
            'FGROUP' => 'payment',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 200,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => true,
            'TYPE' => 'TEXT',
            'STEP' => 6,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'mySessions' => [
            'TYPE' => 'FK',
            'ANSWER' => 'student_session',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'ITEMS',
            'ITEM' => '',
            'WHERE' =>
                'school_id = §school_id§ and
				 levels_template_id = §levels_template_id§ and
				 school_level_order = §school_level_order§ and
				 level_class_order = §level_class_order§ and
				 class_name = §class_name§ and
				 year = §year§ and
				 semester = §semester§ and
				 student_id = §student_id§ ',

            'SHOW' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'VIEW-ICON' => false,
            'FORMAT' => 'retrieve',
            'EDIT' => false,
            'QEDIT' => false,
            'NO-LABEL' => true,
            'BUTTONS' => true,
            'DO-NOT-RETRIEVE-COLS' => [
                0 => 'school_id',
                1 => 'year',
                2 => 'semester',
                3 => 'class_name',
                4 => 'levels_template_id',
                5 => 'school_level_order',
                6 => 'level_class_order',
                7 => 'student_id',                
            ],
            'FORCE-RETRIEVE-COLS' => [
                0 => 'session_date',
                1 => 'session_start_time',
            ],
            'NOWRAP-COLS' => [
                'session_date' => true,
                'coming_status_id' => true,
                'exit_status_id' => true,
            ],
            'FGROUP' => 'stdn',
            'STEP' => 7,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'courses' => array(
            'TYPE' => 'FK',  'ANSWER' => 'student_file_course',  'ANSMODULE' => 'sis',  
            'CATEGORY' => 'ITEMS',  'ITEM' => '', 
            
            'WHERE' => "student_id=§student_id§ 
                     and school_id=§school_id§ 
                     and year=§year§ 
                     and levels_template_id=§levels_template_id§ 
                     and school_level_order=§school_level_order§ 
                     and level_class_order=§level_class_order§ 
					 and class_name=_utf8§class_name§
                     and 1 = 1
                     ", 

            'DO-NOT-RETRIEVE-COLS' => ['student_id', ],
            'FORCE-RETRIEVE-COLS' => ['course_id', ],                 
            'SHOW' => true,  'ICONS' => true,  'DELETE-ICON' => false,  
            'FORMAT' => 'retrieve',  
            'EDIT' => false, 'QEDIT' => false,
            'NO-LABEL' => true,  'BUTTONS' => false,    'DISPLAY' => true,  'STEP' => 8,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_100',),

        'created_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'created_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'DATETIME',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'updated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'updated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'DATETIME',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'validated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'validated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'DATETIME',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'active' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'DEFAUT' => 'Y',
            'TYPE' => 'YN',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'QEDIT' => false,
        ],

        'version'                  => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),

			// 'draft'                         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 
			//                                        'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),

			'update_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
							'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

			'delete_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
							'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

			'display_groups_mfk'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
							'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

			'sci_id'                        => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
                            'QEDIT' => false, 
							'TYPE' => 'FK', 'ANSWER' => 'scenario_item', 'ANSMODULE' => 'pag', 'FGROUP' => 'tech_fields'),

			'tech_notes' 	                => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA', 
                            'QEDIT' => false, "SHOW-ADMIN" => true, 
							'TOKEN_SEP'=>"§", 'READONLY'=>true, "NO-ERROR-CHECK"=>true, 'FGROUP' => 'tech_fields'),	
    ];
}
