<?php
class SisStudentSessionAfwStructure
{
    public static function initInstance(&$obj)
    {
        if($obj instanceof StudentSession)
        {
            $multiple_key_cols = "school_id,levels_template_id,school_level_order,level_class_order,class_name,session_date,session_order,student_id";
            $part_cols = "school_id,school_level_order,level_class_order";
            $context_cols = "";

            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->HIDE_DISPLAY_MODE = true;
            $obj->hideQeditCommonFields = true;
            $obj->DISPLAY_FIELD = "";
            $obj->ORDER_BY_FIELDS = $multiple_key_cols;
            $obj->PK_MULTIPLE = "|";
            $obj->PK_MULTIPLE_ARR = explode(",",$multiple_key_cols);
            $obj->UNIQUE_KEY = $obj->PK_MULTIPLE_ARR;
            $obj->editByStep = true;
            $obj->editNbSteps = 7;
            
            $obj->setContextAndPartitionCols($part_cols, $context_cols);
            $obj->setMultiplePK($multiple_key_cols,$obj->PK_MULTIPLE);
            //$obj->showQueryAndHalt = true;
        }        
    }

    public static $DB_STRUCTURE = [
        'school_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'school',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'DEFAULT-SEARCH' => '§CONTEXT_ID§',
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'levels_template_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'levels_template',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => false,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'school_level_order' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'QEDIT' => true,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'INT',
            'DISPLAY' => false,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'level_class_order' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'QEDIT' => true,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'INT',
            'DISPLAY' => false,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'class_name' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'SIZE' => 1,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => true,
            'TYPE' => 'TEXT',
            'SIZE' => 32,
            'UTF8' => true,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'session_date' => [
            'TYPE' => 'GDAT',
            'SHOW' => true,
            'RETRIEVE' => true,
            'DISPLAY' => true,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'session_order' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => true,
            'TYPE' => 'INT',
            'DISPLAY' => true,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'course_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'course',
            'SHORTNAME' => 'course',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'RELATION' => 'OneToMany',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        

		'year' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            //'ANSWER' => 'FUNCTION',
            'READONLY' => true,
            'MANDATORY' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],

		'semester' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'EDIT' => false,
            'READONLY' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'MANDATORY' => false,
            'DISPLAY' => false,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],

        'session_status_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'session_status',
            'CATEGORY' => 'FORMULA',            
            'READONLY' => true,
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => false,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'student_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'student',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => true,
        ],

        'course_session' => [
            'CATEGORY' => 'FORMULA',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'course_session',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => false,
            'ANSMODULE' => 'sis',
            'DISPLAY' => false,
            'STEP' => 7,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
            'READONLY' => true,
            'RELATION' => 'OneToMany',
        ],

        

        'coming_status_id' => [
            'IMPORTANT' => 'HIGH',
            'SEARCH' => true,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'RETRIEVE' => true,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'TYPE' => 'ENUM',
            'ANSWER' => 'FUNCTION',
            'SIZE' => 40,
            'DEFAULT' => 4,
            'HZM-CSS' =>
                '4,good_quitted|3,absent|2,on_late|1,on_time',
            'FORMAT-INPUT' => 'hzmtoggle',
            'DEFAULT-CSS' => 'not_called_yet',
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'coming_time' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'SEARCH-ADMIN' => true,
            
            'UTF8' => true,
            'TYPE' => 'TIME',
            'ANSWER_METHOD'=>'getComingTimeList', 'FORMAT' => 'OBJECT',  
            'PLACE-HOLDER' => '00:00',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'exit_status_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' =>false,
            'EDIT' => true,
            'QEDIT' => false,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'TYPE' => 'ENUM',
            'ANSWER' => 'FUNCTION',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'HZM-CSS' =>
                '4,good_quitted|3,absent|2,early_quitted|1,on_time',
            'FORMAT-INPUT' => 'hzmtoggle',
            'DEFAULT-CSS' => 'not_called_yet',
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'exit_time' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            
            'UTF8' => true,
            'TYPE' => 'TIME',
            'ANSWER_METHOD'=>'getExitTimeList', 'FORMAT' => 'OBJECT', 
            'PLACE-HOLDER' => '00:00',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],




        

        'mainwork_start_book_id' => [
            'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            "NO-COTE"=>true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'DEPENDENT_OFME' => array("mainwork_start_part_id", "mainwork_start_chapter_id",),
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],
        
        'mainwork_start_part_id' => [
            'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            "NO-COTE"=>true,
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §mainwork_start_book_id§',
            'DEPENDENCY' => 'mainwork_start_book_id',
            'DEPENDENT_OFME' => array("mainwork_start_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        
        'mainwork_start_chapter_id' => [
            'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§mainwork_start_part_id§,%'",
            'DEPENDENCIES' => ['mainwork_start_book_id','mainwork_start_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'mainwork_start_page_num' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'mainwork_end_book_id' => [
            'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            "NO-COTE"=>true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'DEPENDENT_OFME' => array("mainwork_end_part_id", "mainwork_end_chapter_id",),
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],
        
        'mainwork_end_part_id' => [
            'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            "NO-COTE"=>true,
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §mainwork_end_book_id§',
            'DEPENDENCY' => 'mainwork_end_book_id',
            'DEPENDENT_OFME' => array("mainwork_end_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        
        'mainwork_end_chapter_id' => [
            'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§mainwork_end_part_id§,%'",
            'DEPENDENCIES' => ['mainwork_end_book_id','mainwork_end_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'mainwork_end_page_num' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'mainwork_start_paragraph_num' => [
            'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'INT',
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShortFromTo',
                         'buttonTitleObjectAttribute'=>'mainwork_start',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_mainwork_aya_interval',                   
                         
                        ],
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
            
        ],

        'mainwork_start_paragraph_id' => [
            'FGROUP' => 'mainwork',
            'CATEGORY' => 'FORMULA',
            'SEARCH' => false,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book_paragraph',
            'ANSMODULE' => 'sis',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'RELATION-SUPER' => 'IMPORTANT'
        ],

        

        'mainwork_end_paragraph_num' => [
            'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => true,
            
            'TYPE' => 'INT',
            /*'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShort',
                         'buttonTitleObjectAttribute'=>'mainwork_end',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_mainwork_end_aya',                   
                         
                        ],*/
            'NO-LABEL' => true,
            'DISPLAY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            
            'CSS' => 'width_pct_100',
        ],

        
        'homework_start_book_id' => [
            'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'NO-COTE' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            
        ],

        



        'homework_start_part_id' => [
            'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §homework_start_book_id§',
            'DEPENDENCY' => 'homework_start_book_id',
            'DEPENDENT_OFME' => array("homework_start_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        'homework_start_chapter_id' => [
            'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§homework_start_part_id§,%'",
            'DEPENDENCIES' => ['homework_start_book_id','homework_start_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'homework_start_page_num' => [
            'FGROUP' => 'homework',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => false,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],
        

        'homework_end_book_id' => [
            'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'NO-COTE' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            
        ],

        



        'homework_end_part_id' => [
            'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §homework_end_book_id§',
            'DEPENDENCY' => 'homework_end_book_id',
            'DEPENDENT_OFME' => array("homework_end_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        'homework_end_chapter_id' => [
            'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§homework_end_part_id§,%'",
            'DEPENDENCIES' => ['homework_end_book_id','homework_end_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        
        'homework_end_page_num' => [
            'FGROUP' => 'homework',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => false,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],


        'homework_start_paragraph_num' => [
            'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'TYPE' => 'INT',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'READONLY' => false,
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShortFromTo',
                         'buttonTitleObjectAttribute'=>'homework_start',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_homework_aya_interval',                   
                         
                        ],
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'homework_end_paragraph_num' => [
            'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'TYPE' => 'INT',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'READONLY' => true,
            /*
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShort',
                         'buttonTitleObjectAttribute'=>'homework_end',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_homework_end_aya',                   
                         
                        ],*/
            'NO-LABEL' => true,
            'DISPLAY' => false,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        

       

        'homework2_start_book_id' => [
            'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            
        ],

        
        
        'homework2_start_part_id' => [
            'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §homework2_start_book_id§',
            'DEPENDENCY' => 'homework2_start_book_id',
            'DEPENDENT_OFME' => array("homework2_start_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        'homework2_start_chapter_id' => [
            'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§homework2_start_part_id§,%'",
            'DEPENDENCIES' => ['homework2_start_book_id','homework2_start_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'homework2_start_page_num' => [
            'FGROUP' => 'homework2',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => false,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],
        

        

        'homework2_end_book_id' => [
            'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            
        ],

        
        
        'homework2_end_part_id' => [
            'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §homework2_end_book_id§',
            'DEPENDENCY' => 'homework2_book_id',
            'DEPENDENT_OFME' => array("homework2_end_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        'homework2_end_chapter_id' => [
            'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§homework2_end_part_id§,%'",
            'DEPENDENCIES' => ['homework2_end_book_id','homework2_end_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'homework2_end_page_num' => [
            'FGROUP' => 'homework2',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => false,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework2_start_paragraph_num' => [
            'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'TYPE' => 'INT',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => false,
            'DISPLAY' => true,
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShortFromTo',
                         'buttonTitleObjectAttribute'=>'homework2_start',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_homework2_aya_interval',                   
                         
                        ],
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'homework2_end_paragraph_num' => [
            'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'TYPE' => 'INT',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => true,
            /*
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShort',
                         'buttonTitleObjectAttribute'=>'homework2_end',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_homework2_end_aya',                   
                         
                        ],
                        */
            'NO-LABEL' => true,
            'DISPLAY' => false,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'mainwork_rank_id' => [
            'IMPORTANT' => 'HIGH',
            'SEARCH' => true,
            'RETRIEVE' => true,
            'SHOW' => true,
            'EDIT' => true,
            'SIZE' => 1,
            'TYPE' => 'ENUM',
            'ANSWER' =>
                '1,لم ينجر|2,&#9734;|3,&#9734;&#9734;|4,&#9734;&#9734;&#9734;|5,&#9734;&#9734;&#9734;&#9734;|6,&#9734;&#9734;&#9734;&#9734;&#9734;',
                // '1,لم يقم به|2,ناقص|3,يوجد أخطاء|4,جيد|5,جيد جدا|6,ممتاز',
            'QSEARCH' => true,
            'FORMAT-INPUT' => 'hzmtoggle',
            'HZM-CSS' =>
                '6,excellent|5,verygood|4,good|3,accepted|2,poor|1,verypoor',
            'DEFAULT-CSS' => 'notevaluated',
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'mainwork_mistakes' => [
            //'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            'TYPE' => 'INT',
            'EDIT' => true,
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:100:1',
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework_rank_id' => [
            'IMPORTANT' => 'HIGH',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'SIZE' => 1,
            'TYPE' => 'ENUM',
            'ANSWER' =>
                '1,لم ينجر|2,&#9734;|3,&#9734;&#9734;|4,&#9734;&#9734;&#9734;|5,&#9734;&#9734;&#9734;&#9734;|6,&#9734;&#9734;&#9734;&#9734;&#9734;',
            'QSEARCH' => true,
            'FORMAT-INPUT' => 'hzmtoggle',
            'HZM-CSS' =>
                '6,excellent|5,verygood|4,good|3,accepted|2,poor|1,verypoor',
            'DEFAULT-CSS' => 'notevaluated',
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework_mistakes' => [
            //'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'TYPE' => 'INT',
            'RETRIEVE' => false,
            'EDIT' => true,
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:100:1',
            'SHOW' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework2_rank_id' => [
            'IMPORTANT' => 'HIGH',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'SIZE' => 1,
            'TYPE' => 'ENUM',
            'ANSWER' =>
                '1,لم ينجر|2,&#9734;|3,&#9734;&#9734;|4,&#9734;&#9734;&#9734;|5,&#9734;&#9734;&#9734;&#9734;|6,&#9734;&#9734;&#9734;&#9734;&#9734;',
            'QSEARCH' => true,
            'FORMAT-INPUT' => 'hzmtoggle',
            'HZM-CSS' =>
                '6,excellent|5,verygood|4,good|3,accepted|2,poor|1,verypoor',
            'DEFAULT-CSS' => 'notevaluated',
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        
        'homework2_mistakes' => [
            //'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'TYPE' => 'INT',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:100:1',
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],


        'mainwork' => [
            'FGROUP' => 'mainwork',
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => true,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'TEXT',
            'SIZE' => 48,
            'CATEGORY' => 'FORMULA',
            'STEP' => 1,
            'CSS' => 'width_pct_75',
        ],

        'homework' => [
            'FGROUP' => 'homework',
            'IMPORTANT' => 'IN',
            'SEARCH' => false,
            'SHOW' => false,
            'RETRIEVE' => true,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'TEXT',
            'SIZE' => 48,
            'CATEGORY' => 'FORMULA',
            'STEP' => 1,
            'CSS' => 'width_pct_75',
        ],

        'homework2' => [
            'FGROUP' => 'homework2',
            'IMPORTANT' => 'IN',
            'SEARCH' => false,
            'SHOW' => false,
            'RETRIEVE' => true,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'TEXT',
            'SIZE' => 48,
            'CATEGORY' => 'FORMULA',
            'STEP' => 1,
            'CSS' => 'width_pct_75',
        ],



        'moral_rank_id' => [
            'SEARCH' => true,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 1,
            'TYPE' => 'ENUM',
            'ANSWER' =>
                '1,سيئة جدا|2,سيئة|3,مقبولة|4,عالية|5,عالية جدا|6,ممتازة',
            'DEFAULT' => 4,
            'QSEARCH' => true,
            'FORMAT-INPUT' => 'hzmtoggle',
            'HZM-CSS' =>
                '6,excellent|5,verygood|4,good|3,accepted|2,poor|1,verypoor',
            'DEFAULT-CSS' => 'good',
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'interest_rank_id' => [
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 1,
            'TYPE' => 'ENUM',
            'ANSWER' => '1,ضعيف جدا|2,ضعيف|3,مقبول|4,جيد|5,جيد جدا|6,ممتاز',
            'DEFAULT' => 4,
            'QSEARCH' => true,
            'FORMAT-INPUT' => 'hzmtoggle',
            'HZM-CSS' =>
                '6,excellent|5,verygood|4,good|3,accepted|2,poor|1,verypoor',
            'DEFAULT-CSS' => 'good',
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'attendanceList' => [
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'course_session.attendanceList',
            'SHORTCUT-CATEGORY' => 'FORMULA',
            'SUB-CATEGORY' => 'ITEMS',
            'SHOW' => true,
            'EDIT' => true,
            
            'FORMAT' => 'retrieve',
            'READONLY' => true,
            'TYPE' => 'MFK',
            'ANSWER' => 'student_session',
            'ANSMODULE' => 'sis',
            'NO-SAVE' => true,
            'COLSPAN' => 3,
            'DO-NOT-RETRIEVE-COLS' => [
                'school_id',
                'levels_template_id',
                'school_level_order',
                'level_class_order',
                'class_name',
                'session_date',
                'session_order',
            ],
            'NEW-TR' => true,
            'NO-LABEL' => false,
            'BUTTONS' => true,
            'ICONS' => true,
            'DELETE-ICON' => false,
            'VIEW-ICON' => false,
            'EDIT-ICON' => true,
            'STEP' => 6,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],


        'student_file' => [
            'TYPE' => 'FK',
            'FGROUP' => 'mainwork',
            'ANSWER' => 'student_file',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'FORMULA', 
            'WHERE' => "", 
            'SHOW' => true,  
            'EDIT' => true,  'READONLY' => true, 'DISPLAY' => false, 'NO-LABEL' => true, 
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_100',
            'RELATION' => 'OneToMany',
            'STEP' => 1,
            'STEPS' => [1,2,3,4,5],
        ],

        'student_file_course' => [
            'TYPE' => 'FK',
            'ANSWER' => 'student_file_course',
            'ANSMODULE' => 'sis',
            'CATEGORY' => 'FORMULA', 
            'WHERE' => "", 
            'SHOW' => false,  
            'EDIT' => false,  'READONLY' => true, 'DISPLAY' => false, 'NO-LABEL' => true, 
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
            'CSS' => 'width_pct_100',
            'RELATION' => 'OneToMany',
            'STEP' => 1,
            'FGROUP' => 'mainwork',
            //'STEPS' => [1,2,3,4,5],
        ],

        

        'created_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'created_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'GDAT',
            
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'GDAT',
            
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'TYPE' => 'GDAT',
            
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'active' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'DEFAUT' => 'Y',
            'TYPE' => 'YN',
            
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

'version'                  => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),

'update_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

'delete_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

'display_groups_mfk'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
        'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

'sci_id'                        => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 
        'TYPE' => 'FK', 'ANSWER' => 'scenario_item', 'ANSMODULE' => 'pag', 'FGROUP' => 'tech_fields'),

'tech_notes' 	                => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA', "SHOW-ADMIN" => true, 
        'TOKEN_SEP'=>"§", 'READONLY'=>true, "NO-ERROR-CHECK"=>true, 'FGROUP' => 'tech_fields'),	
    ];
}
?>
