<?php
class SisStudentFileCourseAfwStructure
{
    public static function initInstance(&$obj)
    {
        if($obj instanceof StudentFileCourse)
        {
            $multiple_key_cols = "student_id,school_id,year,levels_template_id,school_level_order,level_class_order,course_id";
            $part_cols = "student_id";
            $context_cols = "";

            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            //$obj->QEDIT_SUBMIT_BTN_EACH_RECORD = 1; obsolete replaced by last 3rd returned param from qeditHeaderFooterEmbedded
            // $obj->HIDE_DISPLAY_MODE = true;
            // $obj->hideQeditCommonFields = true;
            $obj->DISPLAY_FIELD = "";
            $obj->ORDER_BY_FIELDS = $multiple_key_cols;
            $obj->PK_MULTIPLE = "|";
            $obj->PK_MULTIPLE_ARR = explode(",",$multiple_key_cols);
            $obj->UNIQUE_KEY = $obj->PK_MULTIPLE_ARR;
            $obj->editByStep = true;
            $obj->editNbSteps = 6;
            
            $obj->setContextAndPartitionCols($part_cols, $context_cols);
            $obj->setMultiplePK($multiple_key_cols,$obj->PK_MULTIPLE);

        }        
    }

    public static $DB_STRUCTURE = [

        'student_id' => ['STEP' => 6,
            'QEDIT_ALL_FGROUP'=>true,
            
            'SHORTNAME' => 'student',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'SIZE' => 40,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'student',
            'ANSMODULE' => 'sis',
            'MANDATORY' => true,
            'RELATION' => 'OneToMany',
            // 'PILLAR' => false,
            'DEFAUT' => 0,
            'AUTOCOMPLETE' => false,
            'WHERE' =>
                'id in (select student_id from c0sis.scandidate where school_id=§school_id§ and year=§year§ and level_class_id=§level_class_id§)', 
            'DISPLAY' => true,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],


        'study_program_id' => array('SHORTNAME' => 'config',  'SEARCH' => true,  
            'FGROUP' => 'manhaj',
            'IMPORTANT' => 'high',
            'QSEARCH' => false,  'SHOW' => true, 
            'RETRIEVE' => true,  'EDIT' => true, 
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true, 
            'QEDIT-BEFORE-COLS' => 1,   
            'SIZE' => 40,  'UTF8' => false,  
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,  'ANSWER' => 'study_program', 
            // to see how to show only study programs that are global (for all schools or for current school) 
            // for the moment the global courses_config_template_id = 3 (for assaf) is available for all schools
            // and course_id = 5 حفظ ومراجعة القرآن
            // for current school we need to calculate formula to get courses_config_template_id
            // for school of current authenticated user
            'WHERE' => "courses_config_template_id = 3 and course_id = 5",
            'DEFAUT' => 0,  'MINIBOX' => true, 
            'ANSMODULE' => 'sis',  'STEP' => 1,  
            'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'RELATION' => 'ManyToOne',
            'CSS' => 'width_pct_25',),  

        'mainwork_sens' => [
                'FGROUP' => 'manhaj',
                'TYPE' => 'ENUM',
                'ANSWER' => "FUNCTION",
                'RETRIEVE' => false,
                'SHOW' => true,
                'EDIT' => true,
                'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
                'QEDIT-BEFORE-COLS' => 1,
                'READONLY' => false,
                'STEP' => 1,
                'DISPLAY-UGROUPS' => '',
                'EDIT-UGROUPS' => '',
                'CSS' => 'width_pct_25',
            ],    
            
            
        'mainwork_nb_parts' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'INT',
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:30:1',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'mainwork_nb_pages' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'INT',
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:30:1',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'mainwork_nb_lines' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'INT',
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:600:1',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        

        'mainwork_stop' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'READONLY' => false,
            'STEP' => 1,
            'DEFAULT' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],

        'mainwork_update' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'YN',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => false,
            'QEDIT' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'DEFAUT' => 'Y',
        ],

        'homework_nb_parts' => [
            'FGROUP' => 'homework',
            'TYPE' => 'INT',
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:30:1',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework_nb_pages' => [
            'FGROUP' => 'homework',
            'TYPE' => 'INT',
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:30:1',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework_nb_lines' => [
            'FGROUP' => 'homework',
            'TYPE' => 'INT',
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:600:1',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework_sens' => [
            'FGROUP' => 'homework',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false, /* 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  */
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework_stop' => [
            'FGROUP' => 'homework',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'READONLY' => false,
            'DEFAULT' => 5,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],

        'homework_update' => [
            'FGROUP' => 'homework',
            'TYPE' => 'YN',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'DEFAUT' => 'Y',
        ],

        'homework2_nb_parts' => [
            'FGROUP' => 'homework2',
            'TYPE' => 'INT',
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:30:1',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework2_nb_pages' => [
            'FGROUP' => 'homework2',
            'TYPE' => 'INT',
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:30:1',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework2_nb_lines' => [
            'FGROUP' => 'homework2',
            'TYPE' => 'INT',
            'EDITOR-STYLE' => 'INCREMENT', 'FORMAT'=>'STEP:0:600:1',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-BEFORE-COLS' => 1,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework2_sens' => [
            'FGROUP' => 'homework2',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false, /* 'QEDIT_FGROUP' => false, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  */
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework2_stop' => [
            'FGROUP' => 'homework2',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'READONLY' => false,
            'DEFAULT' => 5,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],

        'homework2_update' => [
            'FGROUP' => 'homework2',
            'TYPE' => 'YN',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'READONLY' => false,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'DEFAUT' => 'Y',
        ],

        'school_id' => ['STEP' => 6,
            
            'SHORTNAME' => 'school',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 40,
            'UTF8' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'school',
            'ANSMODULE' => 'sis',
            'MANDATORY' => true,
            //'PILLAR' => true,
            //'WHERE' => "id = '§SUB_CONTEXT_ID§'",
            'DEFAUT' => 0,
            'DISPLAY' => true,
            'READONLY' => true,
            'DISPLAY-UGROUPS' => '',
            'RELATION' => 'OneToMany',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],

        'year' => ['STEP' => 6,
            
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'QSEARCH' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            // 'ANSWER' => 'FUNCTION',
            'READONLY' => true,
            'MANDATORY' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],

        'levels_template_id' => ['STEP' => 6,
            
            'SEARCH' => true,
            'EDIT' => false,
            'RETRIEVE' => false,
            'UTF8' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'levels_template',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => '',
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'school_level_order' => ['STEP' => 6,
            
            'SEARCH' => true,
            'SHOW' => false,
            'EDIT' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

            

        'level_class_order' => ['STEP' => 6,
            
            'SEARCH' => true,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

                    'level_class_id' => ['STEP' => 6,
                        'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
                        'ANSWER' => 'level_class',
                        'ANSMODULE' => 'sis',
                        'CATEGORY' => 'FORMULA',
                        'QEDIT' => false,
                        'NO-COTE' => true,
                        'DEFAUT' => 0,
                        'READONLY' => true,
                        'DISPLAY' => true,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'CSS' => 'width_pct_100',
                    ],

        'class_name' => ['STEP' => 6,
            
            'SEARCH' => true,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'TYPE' => 'TEXT',
            'SIZE' => 32,
            'QSEARCH' => true,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'UTF8' => true,
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'semester' => ['STEP' => 6,
            
            'SEARCH' => true,
            'SHOW' => true,
            'EDIT' => true,
            'READONLY' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            'MANDATORY' => false,
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'ERROR-CHECK' => true,
            'CSS' => 'width_pct_25',
        ],

                        'school_class_id' => ['STEP' => 6,
                            
                            'SEARCH' => true,
                            'SHOW' => false,
                            'RETRIEVE' => false,
                            'EDIT' => false,
                            'QEDIT' => false,
                            'SIZE' => 40,
                            'UTF8' => false,
                            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
                            'SHORTNAME' => 'sclass',
                            'ANSWER' => 'school_class',
                            'ANSMODULE' => 'sis',
                            'CATEGORY' => 'FORMULA',
                            'DEFAUT' => 0,
                            'RELATION' => 'OneToMany',
                            'DISPLAY-UGROUPS' => '',
                            'EDIT-UGROUPS' => '',
                            'READONLY' => true,
                            'CSS' => 'width_pct_25',
                        ],

        
        'course_id' => ['STEP' => 6,
            'SHORTNAME' => 'course',
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 40,
            'QSEARCH' => true,
            'UTF8' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'course',
            'ANSWERMODULE' => 'sis',
            'AUTOCOMPLETE-SEARCH' => true,
            'AUTOCOMPLETE' => true,
            'CSS' => 'width_pct_25',
            'READONLY' => true,
            'DEFAULT' => 0,
        ],

                            'school_class_course_id' => ['STEP' => 6,
                                
                                'SEARCH' => true,
                                'SHOW' => false,
                                'RETRIEVE' => false,
                                'EDIT' => false,
                                'QEDIT' => false,
                                'SIZE' => 40,
                                'UTF8' => false,
                                'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
                                'SHORTNAME' => 'sclass',
                                'ANSWER' => 'school_class_course',
                                'ANSMODULE' => 'sis',
                                'CATEGORY' => 'FORMULA',
                                'DEFAUT' => 0,
                                'RELATION' => 'OneToMany',
                                'DISPLAY-UGROUPS' => '',
                                'EDIT-UGROUPS' => '',
                                'READONLY' => true,
                                'CSS' => 'width_pct_25',
                            ],

                            'student_book' => ['STEP' => 6,
                                
                                'SEARCH' => true,
                                'SHOW' => true,
                                'RETRIEVE' => false,
                                'EDIT' => true,
                                'QEDIT' => false,
                                'SIZE' => 40,
                                'UTF8' => false,
                                'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
                                'SHORTNAME' => 'sbook',
                                'ANSWER' => 'student_book',
                                'ANSMODULE' => 'sis',
                                'CATEGORY' => 'FORMULA',
                                'DEFAUT' => 0,
                                'RELATION' => 'OneToMany',
                                'DISPLAY-UGROUPS' => '',
                                'EDIT-UGROUPS' => '',
                                'READONLY' => true,
                                'CSS' => 'width_pct_25',
                            ],
        
                            'mainwork_real_book_id' => [
                                'CATEGORY' => 'FORMULA',
                                'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
                                'ANSWER' => 'cpc_book',
                                'ANSMODULE' => 'sis',
                                'STEP' => 99,
                                'QEDIT' => false,
                            ],

                            'homework_real_book_id' => [
                                'CATEGORY' => 'FORMULA',
                                'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
                                'ANSWER' => 'cpc_book',
                                'ANSMODULE' => 'sis',
                                'STEP' => 99,
                                'QEDIT' => false,
                            ],

                            'homework2_real_book_id' => [
                                'CATEGORY' => 'FORMULA',
                                'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
                                'ANSWER' => 'cpc_book',
                                'ANSMODULE' => 'sis',
                                'STEP' => 99,
                                'QEDIT' => false,
                            ],

        'mainwork_start_book_id' => [
            'FGROUP' => 'mainwork',
            
            'SEARCH' => true,
            "NO-COTE"=>true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'DEPENDENT_OFME' => array("mainwork_start_part_id", "mainwork_start_chapter_id",),
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],
        
        'mainwork_start_part_id' => [
            'FGROUP' => 'mainwork',
            
            "NO-COTE"=>true,
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-COLS' => 2,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §mainwork_real_book_id§',
            'DEPENDENCY' => 'mainwork_start_book_id',
            'DEPENDENT_OFME' => array("mainwork_start_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        
        'mainwork_start_chapter_id' => [
            'FGROUP' => 'mainwork',
            
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-COLS' => 1,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§mainwork_start_part_id§,%'",
            'DEPENDENCIES' => ['mainwork_start_book_id','mainwork_start_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'mainwork_start_page_num' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'ENUM',
            'QEDIT-TYPE' => 'INT',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false, 
            // 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            // 'QEDIT-COLS' => 1,
            'READONLY' => false,
            'READONLY_FGROUP' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'mainwork_end_book_id' => [
            'FGROUP' => 'mainwork',
            
            'SEARCH' => true,
            "NO-COTE"=>true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'DEPENDENT_OFME' => array("mainwork_end_part_id", "mainwork_end_chapter_id",),
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],
        
        'mainwork_end_part_id' => [
            'FGROUP' => 'mainwork',
            
            "NO-COTE"=>true,
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => false, /* 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 2,*/
            'EDIT' => true,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §mainwork_real_book_id§',
            'DEPENDENCY' => 'mainwork_end_book_id',
            'DEPENDENT_OFME' => array("mainwork_end_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        
        'mainwork_end_chapter_id' => [
            'FGROUP' => 'mainwork',
            
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 2,
            'EDIT' => true,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§mainwork_end_part_id§,%'",
            'DEPENDENCIES' => ['mainwork_end_book_id','mainwork_end_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'mainwork_end_page_num' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'ENUM',
            'QEDIT-TYPE' => 'INT',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false, 
            // 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            // 'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 1,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'mainwork_reel_end_page_num' => [
            'FGROUP' => 'mainwork',
            'TYPE' => 'ENUM', 
            'QEDIT-TYPE' => 'INT',
            'CATEGORY' => 'FORMULA',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 
            'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 1,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'mainwork_start_paragraph_num' => [
            'FGROUP' => 'mainwork',
            
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-COLS' => 1,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'INT',
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShortFromTo',
                         'buttonTitleObjectAttribute'=>'mainwork_start',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_mainwork_aya_interval',                   
                         
                        ],
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
            
        ],

                    'mainwork_start_paragraph_id' => [
                        'FGROUP' => 'mainwork',
                        'CATEGORY' => 'FORMULA',
                        'SEARCH' => false,
                        'SHOW' => false,
                        'RETRIEVE' => false,
                        'QEDIT' => false,
                        'EDIT' => false,
                        'READONLY' => true,
                        'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
                        'ANSWER' => 'cpc_book_paragraph',
                        'ANSMODULE' => 'sis',
                        'SIZE' => 40,
                        'DEFAUT' => 0,
                        'QSEARCH' => true,
                        'STEP' => 2,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'CSS' => 'width_pct_50',
                        'RELATION-SUPER' => 'IMPORTANT'
                    ],

        

        'mainwork_end_paragraph_num' => [
            'FGROUP' => 'mainwork',
            
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 1,
            'EDIT' => true,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            
            'TYPE' => 'INT',
            /*'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShort',
                         'buttonTitleObjectAttribute'=>'mainwork_end',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_mainwork_end_aya',                   
                         
                        ],*/
            'NO-LABEL' => true,
            'DISPLAY' => false,
            'STEP' => 2,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            
            'CSS' => 'width_pct_100',
        ],

        
        'homework_start_book_id' => [
            'FGROUP' => 'homework',
            
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'NO-COTE' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            
        ],

        



        'homework_start_part_id' => [
            'FGROUP' => 'homework',
            
            'SEARCH' => true,
            'SHOW' => true,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-COLS' => 2,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §homework_real_book_id§',
            'DEPENDENCY' => 'homework_start_book_id',
            'DEPENDENT_OFME' => array("homework_start_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        'homework_start_chapter_id' => [
            'FGROUP' => 'homework',
            
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-COLS' => 1,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§homework_start_part_id§,%'",
            'DEPENDENCIES' => ['homework_start_book_id','homework_start_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'homework_start_page_num' => [
            'FGROUP' => 'homework',
            'TYPE' => 'ENUM',
            'QEDIT-TYPE' => 'INT',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false, 
            // 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            // 'QEDIT-COLS' => 1,
            'READONLY' => false,
            'READONLY_FGROUP' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],
        

        'homework_end_book_id' => [
            'FGROUP' => 'homework',
            
            'SEARCH' => true,
            'SHOW' => false,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'NO-COTE' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            
        ],

        



        'homework_end_part_id' => [
            'FGROUP' => 'homework',
            
            'SEARCH' => true,
            'SHOW' => true,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false, /* 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 2,*/
            'EDIT' => true,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §homework_real_book_id§',
            'DEPENDENCY' => 'homework_end_book_id',
            'DEPENDENT_OFME' => array("homework_end_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        'homework_end_chapter_id' => [
            'FGROUP' => 'homework',
            
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 2,
            'EDIT' => true,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§homework_end_part_id§,%'",
            'DEPENDENCIES' => ['homework_end_book_id','homework_end_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        
        'homework_end_page_num' => [
            'FGROUP' => 'homework',
            'TYPE' => 'ENUM',
            'QEDIT-TYPE' => 'INT',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false, 
            'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 1,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],


        'homework_start_paragraph_num' => [
            'FGROUP' => 'homework',
            
            'TYPE' => 'INT',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-COLS' => 1,
            'READONLY' => false,
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShortFromTo',
                         'buttonTitleObjectAttribute'=>'homework_start',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_homework_aya_interval',                   
                         
                        ],
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'homework_end_paragraph_num' => [
            'FGROUP' => 'homework',
            
            'TYPE' => 'INT',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 1,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            /*
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShort',
                         'buttonTitleObjectAttribute'=>'homework_end',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_homework_end_aya',                   
                         
                        ],*/
            'NO-LABEL' => true,
            'DISPLAY' => false,
            'STEP' => 3,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        

       

        'homework2_start_book_id' => [
            'FGROUP' => 'homework2',
            
            'SEARCH' => true,
            'SHOW' => false,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            
        ],

        
        
        'homework2_start_part_id' => [
            'FGROUP' => 'homework2',
            
            'SEARCH' => true,
            'SHOW' => true,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-COLS' => 2,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §homework2_real_book_id§',
            'DEPENDENCY' => 'homework2_start_book_id',
            'DEPENDENT_OFME' => array("homework2_start_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        'homework2_start_chapter_id' => [
            'FGROUP' => 'homework2',
            
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-COLS' => 1,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§homework2_start_part_id§,%'",
            'DEPENDENCIES' => ['homework2_start_book_id','homework2_start_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'homework2_start_page_num' => [
            'FGROUP' => 'homework2',
            'QEDIT-TYPE' => 'INT',
            'TYPE' => 'ENUM',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false, 
            // 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            // 'QEDIT-COLS' => 1,
            'READONLY' => false,
            'READONLY_FGROUP' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],
        

        

        'homework2_end_book_id' => [
            'FGROUP' => 'homework2',
            
            'SEARCH' => true,
            'SHOW' => false,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false,
            'EDIT' => false,
            'READONLY' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            
        ],

        
        
        'homework2_end_part_id' => [
            'FGROUP' => 'homework2',
            
            'SEARCH' => true,
            'SHOW' => true,
            'NO-COTE' => true,
            'RETRIEVE' => false,
            'QEDIT' => false, /* 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 2,*/
            'EDIT' => true,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => 'book_type_id = 2 and parent_book_id = §homework2_real_book_id§',
            'DEPENDENCY' => 'homework2_book_id',
            'DEPENDENT_OFME' => array("homework2_end_chapter_id", ),
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => false,
        ],

        'homework2_end_chapter_id' => [
            'FGROUP' => 'homework2',
            
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 2,
            'EDIT' => true,
            'READONLY' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'cpc_book',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'QSEARCH' => true,
            'WHERE' => "book_type_id = 3 and part_mfk like '%,§homework2_end_part_id§,%'",
            'DEPENDENCIES' => ['homework2_end_book_id','homework2_end_part_id'],
            'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => false,
        ],

        'homework2_end_page_num' => [
            'FGROUP' => 'homework2',
            'TYPE' => 'ENUM',
            'QEDIT-TYPE' => 'INT',
            'ANSWER' => "FUNCTION",
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => false, 
            'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 1,
            'READONLY' => false,
            'READONLY_FGROUP' => true,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'homework2_start_paragraph_num' => [
            'FGROUP' => 'homework2',
            
            'TYPE' => 'INT',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-COLS' => 1,
            'READONLY' => false,
            'DISPLAY' => true,
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShortFromTo',
                         'buttonTitleObjectAttribute'=>'homework2_start',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_homework2_aya_interval',                   
                         
                        ],
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'homework2_end_paragraph_num' => [
            'FGROUP' => 'homework2',
            
            'TYPE' => 'INT',
            'RETRIEVE' => false,
            'SHOW' => true,
            'EDIT' => true,
            'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,  
            'QEDIT-CSS'=>'calculated', 'QEDIT-AFTER-COLS' => 1,
            'READONLY' => true, 'READONLY_FGROUP' => true,
            /*
            'EDITOR' => ['src'=>'sis/tpl/select_ayat.php', 
                         'buttonTitleMethod'=>'paragraphShort',
                         'buttonTitleObjectAttribute'=>'homework2_end',
                         'paramsMethod'=>'getBookParams',
                         'full' => true,
                         'jsFunction'=>'select_homework2_end_aya',                   
                         
                        ],
                        */
            'NO-LABEL' => true,
            'DISPLAY' => false,
            'STEP' => 4,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],


        

            'mainwork' => [
                'FGROUP' => 'mainwork',
                
                'SEARCH' => true,
                'SHOW' => true,
                'RETRIEVE' => true,
                'QEDIT' => false,
                'EDIT' => true,
                'READONLY' => false,
                'TYPE' => 'TEXT',
                'SIZE' => 48,
                'CATEGORY' => 'FORMULA',
                'STEP' => 99,
                'CSS' => 'width_pct_75',
            ],

            'homework' => [
                'FGROUP' => 'homework',
                
                'SEARCH' => true,
                'SHOW' => true,
                'RETRIEVE' => true,
                'QEDIT' => false,
                'EDIT' => true,
                'READONLY' => false,
                'TYPE' => 'TEXT',
                'SIZE' => 48,
                'CATEGORY' => 'FORMULA',
                'STEP' => 99,
                'CSS' => 'width_pct_75',
            ],

            

            'homework2' => [
                'FGROUP' => 'homework2',
                'IMPORTANT' => 'medium',
                'SEARCH' => true,
                'SHOW' => true,
                'RETRIEVE' => true,
                'QEDIT' => false,
                'EDIT' => true,
                'READONLY' => false,
                'TYPE' => 'TEXT',
                'SIZE' => 48,
                'CATEGORY' => 'FORMULA',
                'STEP' => 99,
                'CSS' => 'width_pct_75',
            ],


            'courses' => array(
                'TYPE' => 'FK', 'NO_KEEP_VAL' => true,  
                'CATEGORY' => 'SHORTCUT',
                'SHORTCUT' => 'school_class_course_id.courses',
                'SHORTCUT-CATEGORY' => 'FORMULA',
                'SUB-CATEGORY' => 'ITEMS',
                'ANSWER' => 'student_file_course',  
                'ANSMODULE' => 'sis',  
                'ITEM' => '', 	
                'WHERE' => "school_id=§school_id§ 
                        and year=§year§ 
                        and levels_template_id=§levels_template_id§ 
                        and school_level_order=§school_level_order§ 
                        and level_class_order=§level_class_order§ 
                        and class_name=_utf8§class_name§ 
                        and course_id = §course_id§", 
                 'SHOW' => true,  'ICONS' => true,  'DELETE-ICON' => false, 'EDIT-ICON' => false, 'FORMAT' => 'retrieve',  'EDIT' => false,
                   'NO-LABEL' => true,  'BUTTONS' => false, 'RETRIEVE' => false,   'DISPLAY' => true,  'STEP' => 5,  
                'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
                'CSS' => 'width_pct_100',),
                    
                    

            'course_name_ar' => array('STEP' => 99,  'SEARCH' => true,  'SHOW' => true,  'EXCEL' => true,  
					'EDIT' => true,  'QEDIT' => true, 'QEDIT_FGROUP' => true, 'IMPORTANT' => 'high', 'EDIT_FGROUP' => true, 'SHOW_FGROUP' => true,    'SIZE' => 32,  'QSEARCH' => true,  
					'SHOW-ADMIN' => true,  'EDIT-ADMIN' => true,  'UTF8' => true,  
					'CATEGORY' => 'SHORTCUT', 'SHORTCUT' => 'course_id.course_name_ar',
					'TYPE' => 'TEXT',    'DISPLAY' => true,  'RETRIEVE' => false,
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
					'CSS' => 'width_pct_50',),					

				
					
			

        'created_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'created_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'DATETIME',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'updated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'updated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'DATETIME',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'validated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK', 'NO_KEEP_VAL' => true,
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'validated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'DATETIME',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'active' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'DEFAUT' => 'Y',
            'TYPE' => 'YN',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'version'                  => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),

			// 'draft'                         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 
			//                                        'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),

			'update_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
							'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

			'delete_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
							'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

			'display_groups_mfk'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
							'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),

			'sci_id'                        => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 
							'TYPE' => 'FK', 'NO_KEEP_VAL' => true, 'ANSWER' => 'scenario_item', 'ANSMODULE' => 'pag', 'FGROUP' => 'tech_fields'),

			'tech_notes' 	                => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'RETRIEVE' => false, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA', 'QEDIT' => false, "SHOW-ADMIN" => true, 
							'TOKEN_SEP'=>"§", 'READONLY'=>true, "NO-ERROR-CHECK"=>true, 'FGROUP' => 'tech_fields'),	
    ];
}
